# Decompiled TRAE business class
# Source DEX: classes5.dex
.class public final Lcom/bytedance/trae/conversation/R$dimen;
.super Ljava/lang/Object;

.field public static final trae_action_bar_divider_width:I
.field public static final trae_brainstorm_action_button_size:I
.field public static final trae_brainstorm_action_shadow_blur_radius:I
.field public static final trae_brainstorm_action_shadow_offset_y:I
.field public static final trae_brainstorm_attachment_card_corner_radius:I
.field public static final trae_brainstorm_attachment_close_margin:I
.field public static final trae_brainstorm_attachment_close_padding:I
.field public static final trae_brainstorm_attachment_close_size:I
.field public static final trae_brainstorm_attachment_file_height:I
.field public static final trae_brainstorm_attachment_file_width:I
.field public static final trae_brainstorm_attachment_image_size:I
.field public static final trae_brainstorm_bottom_action_gap:I
.field public static final trae_brainstorm_bottom_action_horizontal_padding:I
.field public static final trae_brainstorm_bottom_status_height:I
.field public static final trae_brainstorm_bottom_status_margin_top:I
.field public static final trae_brainstorm_bottom_status_text_margin_top:I
.field public static final trae_brainstorm_bottom_status_width:I
.field public static final trae_brainstorm_device_item_gap:I
.field public static final trae_brainstorm_device_switcher_min_height:I
.field public static final trae_brainstorm_discuss_top_bar_translation_y:I
.field public static final trae_brainstorm_header_action_button_size:I
.field public static final trae_brainstorm_header_action_gap:I
.field public static final trae_brainstorm_header_action_icon_padding:I
.field public static final trae_brainstorm_header_action_pill_height:I
.field public static final trae_brainstorm_header_action_pill_width:I
.field public static final trae_brainstorm_subtitle_empty_hint_margin_top:I
.field public static final trae_chat_attachment_item_height:I
.field public static final trae_connect_guide_card_stroke_width:I
.field public static final trae_connect_guide_copy_gap:I
.field public static final trae_connect_guide_copy_icon_size:I
.field public static final trae_connect_guide_copy_touch_min_height:I
.field public static final trae_connect_guide_image_corner_radius:I
.field public static final trae_connect_guide_image_steps_gap:I
.field public static final trae_connect_guide_sheet_height:I
.field public static final trae_connect_guide_step_gap:I
.field public static final trae_connect_guide_steps_width:I
.field public static final trae_connect_guide_url_gap:I
.field public static final trae_device_activate_content_padding_bottom:I
.field public static final trae_device_activate_content_padding_top:I
.field public static final trae_device_activate_image_height:I
.field public static final trae_device_activate_sheet_height:I
.field public static final trae_device_activate_text_margin_horizontal:I
.field public static final trae_device_status_chip_min_width:I
.field public static final trae_device_target_select_card_height:I
.field public static final trae_device_target_select_card_padding_horizontal:I
.field public static final trae_device_target_select_card_padding_vertical:I
.field public static final trae_device_target_select_card_radius:I
.field public static final trae_device_target_select_card_stroke_width:I
.field public static final trae_device_target_select_content_padding_bottom:I
.field public static final trae_device_target_select_content_padding_top:I
.field public static final trae_device_target_select_gap:I
.field public static final trae_device_target_select_icon_size:I
.field public static final trae_device_target_select_icon_text_gap:I
.field public static final trae_device_target_select_sheet_height:I
.field public static final trae_device_target_select_subtitle_font_size_sp:I
.field public static final trae_device_target_select_subtitle_line_height_dp:I
.field public static final trae_device_target_select_text_gap:I
.field public static final trae_device_target_select_title_font_size_sp:I
.field public static final trae_device_target_select_title_line_height_dp:I
.field public static final trae_directory_add_button_height:I
.field public static final trae_directory_add_button_padding_horizontal:I
.field public static final trae_directory_add_button_padding_vertical:I
.field public static final trae_directory_bottom_action_height:I
.field public static final trae_dp_0:I
.field public static final trae_dp_12:I
.field public static final trae_dp_14:I
.field public static final trae_dp_16:I
.field public static final trae_dp_18:I
.field public static final trae_dp_2:I
.field public static final trae_dp_20:I
.field public static final trae_dp_24:I
.field public static final trae_dp_28:I
.field public static final trae_dp_32:I
.field public static final trae_dp_36:I
.field public static final trae_dp_4:I
.field public static final trae_dp_48:I
.field public static final trae_dp_8:I
.field public static final trae_html_preview_border_width:I
.field public static final trae_html_preview_button_min_height:I
.field public static final trae_html_preview_button_padding_horizontal:I
.field public static final trae_html_preview_button_padding_vertical:I
.field public static final trae_html_preview_button_radius:I
.field public static final trae_html_preview_icon_card_radius:I
.field public static final trae_html_preview_icon_card_size:I
.field public static final trae_html_preview_icon_size:I
.field public static final trae_html_preview_state_gap:I
.field public static final trae_html_preview_state_horizontal_padding:I
.field public static final trae_input_text_min_height:I
.field public static final trae_input_text_padding_horizontal:I
.field public static final trae_input_text_padding_vertical:I
.field public static final trae_media_choose_border_width:I
.field public static final trae_media_choose_bottom_padding_h:I
.field public static final trae_media_choose_bottom_padding_v:I
.field public static final trae_media_choose_camera_icon_size:I
.field public static final trae_media_choose_duration_margin:I
.field public static final trae_media_choose_duration_padding_h:I
.field public static final trae_media_choose_duration_padding_v:I
.field public static final trae_media_choose_gap:I
.field public static final trae_media_choose_icon_touch_padding_h:I
.field public static final trae_media_choose_notice_padding_h:I
.field public static final trae_media_choose_notice_padding_v:I
.field public static final trae_media_choose_preview_bar_height:I
.field public static final trae_media_choose_preview_select_margin_end:I
.field public static final trae_media_choose_preview_select_margin_top:I
.field public static final trae_media_choose_select_margin:I
.field public static final trae_media_choose_select_size:I
.field public static final trae_media_choose_send_height:I
.field public static final trae_media_choose_send_min_width:I
.field public static final trae_media_choose_send_radius:I
.field public static final trae_media_choose_top_bar_height:I
.field public static final trae_media_choose_vector_icon_size:I
.field public static final trae_minimized_voice_bar_corner_radius:I
.field public static final trae_minimized_voice_bar_elevation:I
.field public static final trae_minimized_voice_bar_height:I
.field public static final trae_minimized_voice_bar_margin_horizontal:I
.field public static final trae_minimized_voice_bar_shadow_margin_vertical:I
.field public static final trae_minimized_voice_button_padding:I
.field public static final trae_minimized_voice_button_size:I
.field public static final trae_minimized_voice_content_gap:I
.field public static final trae_minimized_voice_icon_size:I
.field public static final trae_model_list_content_rate_gap:I
.field public static final trae_model_list_icon_size:I
.field public static final trae_model_list_name_tag_gap:I
.field public static final trae_model_list_row_height:I
.field public static final trae_model_list_tag_height:I
.field public static final trae_model_list_tag_min_width:I
.field public static final trae_model_list_tag_padding_end:I
.field public static final trae_model_list_tag_padding_start:I
.field public static final trae_model_list_tag_radius:I
.field public static final trae_multi_image_preview_action_padding:I
.field public static final trae_multi_image_preview_action_size:I
.field public static final trae_multi_image_preview_download_icon_size:I
.field public static final trae_multi_image_preview_horizontal_padding:I
.field public static final trae_multi_image_preview_title_bar_height:I
.field public static final trae_multi_image_preview_title_side_margin:I
.field public static final trae_new_feature_prompt_button_height:I
.field public static final trae_new_feature_prompt_button_margin_bottom:I
.field public static final trae_new_feature_prompt_image_height:I
.field public static final trae_new_feature_prompt_message_font_size_sp:I
.field public static final trae_new_feature_prompt_message_line_height_dp:I
.field public static final trae_new_feature_prompt_message_margin_horizontal:I
.field public static final trae_new_feature_prompt_message_margin_top:I
.field public static final trae_new_feature_prompt_sheet_height:I
.field public static final trae_new_feature_prompt_title_font_size_sp:I
.field public static final trae_new_feature_prompt_title_line_height_dp:I
.field public static final trae_plugin_authorization_action_gap:I
.field public static final trae_plugin_authorization_action_top_margin:I
.field public static final trae_plugin_authorization_body_line_height:I
.field public static final trae_plugin_authorization_body_text_size:I
.field public static final trae_plugin_authorization_button_border_width:I
.field public static final trae_plugin_authorization_button_height:I
.field public static final trae_plugin_authorization_button_horizontal_padding:I
.field public static final trae_plugin_authorization_button_line_height:I
.field public static final trae_plugin_authorization_button_radius:I
.field public static final trae_plugin_authorization_button_text_size:I
.field public static final trae_plugin_authorization_title_body_gap:I
.field public static final trae_product_type_chip_height:I
.field public static final trae_product_type_chip_line_height:I
.field public static final trae_product_type_chip_margin_top:I
.field public static final trae_product_type_chip_padding_horizontal:I
.field public static final trae_product_type_chip_radius:I
.field public static final trae_pure_show_widget_bootstrap_height:I
.field public static final trae_task_template_item_height:I
.field public static final trae_task_template_item_icon_size:I
.field public static final trae_upgrade_reminder_actions_margin_top:I
.field public static final trae_upgrade_reminder_body_line_height:I
.field public static final trae_upgrade_reminder_body_margin_top:I
.field public static final trae_upgrade_reminder_body_text_size:I
.field public static final trae_upgrade_reminder_button_height:I
.field public static final trae_upgrade_reminder_button_line_height:I
.field public static final trae_upgrade_reminder_button_padding_horizontal:I
.field public static final trae_upgrade_reminder_button_radius:I
.field public static final trae_upgrade_reminder_button_text_size:I
.field public static final trae_upgrade_reminder_card_border_width:I
.field public static final trae_upgrade_reminder_card_padding_horizontal:I
.field public static final trae_upgrade_reminder_card_padding_vertical:I
.field public static final trae_upgrade_reminder_card_radius:I
.field public static final trae_upgrade_reminder_outer_padding_bottom:I
.field public static final trae_upgrade_reminder_outer_padding_horizontal:I
.field public static final trae_upgrade_reminder_outer_padding_top:I
.field public static final trae_upgrade_reminder_title_line_height:I
.field public static final trae_upgrade_reminder_title_text_size:I
.field public static final trae_voice_discussion_confirm_dialog_button_margin_top:I
.field public static final trae_voice_discussion_confirm_dialog_text_padding_horizontal:I
.field public static final trae_voice_discussion_confirm_dialog_width:I
.field public static final trae_voice_discussion_switch_dialog_button_margin_top:I
.field public static final trae_voice_discussion_switch_dialog_button_radius:I
.field public static final trae_voice_discussion_switch_dialog_radius:I
.field public static final trae_voice_discussion_switch_dialog_text_padding_horizontal:I
.field public static final trae_voice_discussion_switch_dialog_width:I
.field public static final trae_voice_history_empty_icon_container_size:I


.method private constructor <init>()void
    .registers 1
    # ins_size=1
    invoke-direct v0, Ljava/lang/Object;-><init>()V
    return-void 
.end method
