# Decompiled TRAE business class
# Source DEX: classes5.dex
.class public final Lcom/bytedance/trae/conversation/R$drawable;
.super Ljava/lang/Object;

.field public static final add:I
.field public static final add_1:I
.field public static final agent:I
.field public static final arrow_down:I
.field public static final arrowleft:I
.field public static final attach_image:I
.field public static final audiowave:I
.field public static final audiowavesmall:I
.field public static final avatar_agent_explore:I
.field public static final avatar_agent_general_purpose:I
.field public static final avatar_agent_plan:I
.field public static final avatar_agent_search:I
.field public static final avatar_coder:I
.field public static final bg_add_device_bottom_sheet:I
.field public static final bg_ai_data_notice_btn:I
.field public static final bg_ai_data_notice_dialog:I
.field public static final bg_artifact_button_download:I
.field public static final bg_artifact_preview_white:I
.field public static final bg_bottom_sheet:I
.field public static final bg_btn_open_in_other_apps:I
.field public static final bg_chat_attachment_close_button:I
.field public static final bg_chat_attachment_dialog:I
.field public static final bg_chat_attachment_handle:I
.field public static final bg_chat_attachment_item:I
.field public static final bg_circle_base_default:I
.field public static final bg_circle_overlay:I
.field public static final bg_circle_shadow:I
.field public static final bg_conversation_detail_menu_popup:I
.field public static final bg_conversation_menu_popup:I
.field public static final bg_device_target_select_card:I
.field public static final bg_device_target_select_sheet:I
.field public static final bg_directory_add_folder_btn:I
.field public static final bg_directory_confirm_btn:I
.field public static final bg_directory_ok_btn:I
.field public static final bg_handle_bar:I
.field public static final bg_new_feature_prompt_connect_button:I
.field public static final bg_plugin_empty_icon:I
.field public static final bg_process_detail_sheet:I
.field public static final bg_starbucks:I
.field public static final bg_starbucks_poster_top_round:I
.field public static final bg_starbucks_save_btn:I
.field public static final bg_starbucks_share_handle:I
.field public static final bg_starbucks_share_item:I
.field public static final bg_starbucks_share_panel:I
.field public static final bg_voice_loading:I
.field public static final browser_use:I
.field public static final checkmark_circle:I
.field public static final checkmark_circle_1:I
.field public static final checkmark_small:I
.field public static final chevron_fold:I
.field public static final chevron_left:I
.field public static final chevron_right:I
.field public static final chevron_right_gray:I
.field public static final chevron_unfold:I
.field public static final circle_progress_arc_static:I
.field public static final circle_progress_determinate:I
.field public static final circle_progress_indeterminate:I
.field public static final circle_progress_track:I
.field public static final close:I
.field public static final close_1:I
.field public static final cloud:I
.field public static final computer:I
.field public static final copy:I
.field public static final document:I
.field public static final edit:I
.field public static final environment_repair:I
.field public static final explorer_eslint:I
.field public static final explorer_eslint_ignore:I
.field public static final explorer_file:I
.field public static final explorer_file_authorization:I
.field public static final explorer_file_preview:I
.field public static final explorer_file_readme:I
.field public static final explorer_file_settings:I
.field public static final explorer_file_user_rule:I
.field public static final explorer_file_workspace:I
.field public static final explorer_file_workspace_rule:I
.field public static final explorer_folder_closed:I
.field public static final explorer_folder_open:I
.field public static final explorer_gitlab:I
.field public static final explorer_lang_bat:I
.field public static final explorer_lang_c:I
.field public static final explorer_lang_c_sharp:I
.field public static final explorer_lang_cpp:I
.field public static final explorer_lang_css:I
.field public static final explorer_lang_dts:I
.field public static final explorer_lang_go:I
.field public static final explorer_lang_html:I
.field public static final explorer_lang_java:I
.field public static final explorer_lang_js:I
.field public static final explorer_lang_json:I
.field public static final explorer_lang_next:I
.field public static final explorer_lang_python:I
.field public static final explorer_lang_python_1:I
.field public static final explorer_lang_react:I
.field public static final explorer_lang_rs:I
.field public static final explorer_lang_ts:I
.field public static final explorer_lang_vue:I
.field public static final explorer_lang_vue_1:I
.field public static final explorer_lang_xml:I
.field public static final explorer_lang_yaml:I
.field public static final explorer_npm:I
.field public static final explorer_type_bash:I
.field public static final explorer_type_class:I
.field public static final explorer_type_command:I
.field public static final explorer_type_doc:I
.field public static final explorer_type_docker:I
.field public static final explorer_type_docx:I
.field public static final explorer_type_function:I
.field public static final explorer_type_git:I
.field public static final explorer_type_header:I
.field public static final explorer_type_ico:I
.field public static final explorer_type_image:I
.field public static final explorer_type_key:I
.field public static final explorer_type_license:I
.field public static final explorer_type_markdown:I
.field public static final explorer_type_markdown_1:I
.field public static final explorer_type_numbers:I
.field public static final explorer_type_pages:I
.field public static final explorer_type_pdf:I
.field public static final explorer_type_pptx:I
.field public static final explorer_type_svg:I
.field public static final explorer_type_txt:I
.field public static final explorer_type_xlsx:I
.field public static final face_error:I
.field public static final file_document:I
.field public static final filetype_diff:I
.field public static final folder:I
.field public static final git_branches:I
.field public static final git_branches_enable:I
.field public static final git_branches_pupple:I
.field public static final glasses_read:I
.field public static final ic_add:I
.field public static final ic_add_device:I
.field public static final ic_add_device_location_close:I
.field public static final ic_arrow_left:I
.field public static final ic_artifact_code:I
.field public static final ic_artifact_custom:I
.field public static final ic_artifact_design_library:I
.field public static final ic_artifact_design_product:I
.field public static final ic_artifact_diff:I
.field public static final ic_artifact_doc:I
.field public static final ic_artifact_excel:I
.field public static final ic_artifact_html:I
.field public static final ic_artifact_jpg:I
.field public static final ic_artifact_json:I
.field public static final ic_artifact_markdown:I
.field public static final ic_artifact_mp3:I
.field public static final ic_artifact_pdf:I
.field public static final ic_artifact_png:I
.field public static final ic_artifact_ppt:I
.field public static final ic_artifact_preview:I
.field public static final ic_artifact_skill:I
.field public static final ic_artifact_txt:I
.field public static final ic_artifact_vedio:I
.field public static final ic_artifact_video:I
.field public static final ic_artifact_zip:I
.field public static final ic_assistant_microphone:I
.field public static final ic_assistant_plus:I
.field public static final ic_avatar_fast:I
.field public static final ic_back_black:I
.field public static final ic_chat_attachment_camera:I
.field public static final ic_chat_attachment_files:I
.field public static final ic_chat_attachment_photo:I
.field public static final ic_chat_attachment_plugins:I
.field public static final ic_chat_attachment_skills:I
.field public static final ic_chat_close:I
.field public static final ic_check:I
.field public static final ic_checkmark:I
.field public static final ic_chevron_down:I
.field public static final ic_chevron_left_figma:I
.field public static final ic_chevron_right:I
.field public static final ic_chevron_right_1:I
.field public static final ic_close:I
.field public static final ic_close_black:I
.field public static final ic_close_express_pass_guide:I
.field public static final ic_close_gray:I
.field public static final ic_computer:I
.field public static final ic_conversation_delete:I
.field public static final ic_conversation_menu_artifact:I
.field public static final ic_conversation_pdf:I
.field public static final ic_conversation_rename:I
.field public static final ic_copy:I
.field public static final ic_device_badge_ide:I
.field public static final ic_device_badge_lite:I
.field public static final ic_device_comptuer_offline:I
.field public static final ic_device_computer_online:I
.field public static final ic_device_folder:I
.field public static final ic_device_offline:I
.field public static final ic_device_online:I
.field public static final ic_device_select_remote:I
.field public static final ic_device_selected:I
.field public static final ic_diff_add:I
.field public static final ic_diff_delete:I
.field public static final ic_diff_edit:I
.field public static final ic_diff_view_extend:I
.field public static final ic_dir_recent_empty:I
.field public static final ic_document_arrow:I
.field public static final ic_error_emoji:I
.field public static final ic_error_face:I
.field public static final ic_explorer_close:I
.field public static final ic_explorer_dot:I
.field public static final ic_explorer_down:I
.field public static final ic_explorer_download:I
.field public static final ic_explorer_folder:I
.field public static final ic_express_pass_banner_close:I
.field public static final ic_file_css:I
.field public static final ic_file_default:I
.field public static final ic_file_diff_large:I
.field public static final ic_file_folder:I
.field public static final ic_file_header:I
.field public static final ic_file_markdown:I
.field public static final ic_file_python:I
.field public static final ic_file_react:I
.field public static final ic_file_rust:I
.field public static final ic_file_warning:I
.field public static final ic_file_zip:I
.field public static final ic_folder:I
.field public static final ic_folder_figma:I
.field public static final ic_hold_to_talk:I
.field public static final ic_identity_no_limit:I
.field public static final ic_input_arrow_down:I
.field public static final ic_input_arrow_up:I
.field public static final ic_input_arrow_up_disable:I
.field public static final ic_input_arrow_up_enable:I
.field public static final ic_input_bar_add:I
.field public static final ic_input_bar_bytecloud:I
.field public static final ic_input_bar_express_999:I
.field public static final ic_input_bar_github:I
.field public static final ic_input_bar_microphone:I
.field public static final ic_input_bar_no_use_express_pass:I
.field public static final ic_input_bar_remote:I
.field public static final ic_input_bar_use_express_pass:I
.field public static final ic_input_bar_voice_chat:I
.field public static final ic_input_device_ide:I
.field public static final ic_input_device_lite:I
.field public static final ic_input_skill:I
.field public static final ic_input_stop:I
.field public static final ic_item_device:I
.field public static final ic_local_off:I
.field public static final ic_local_online:I
.field public static final ic_mcp_tool:I
.field public static final ic_menu_copy:I
.field public static final ic_menu_delete:I
.field public static final ic_menu_revert:I
.field public static final ic_mtc_artifact_down_arrow:I
.field public static final ic_mtc_artifact_left_arrow:I
.field public static final ic_new_conversation:I
.field public static final ic_no_skills:I
.field public static final ic_notify_chevron_right:I
.field public static final ic_open_in_browser:I
.field public static final ic_open_preview_web:I
.field public static final ic_open_preview_web_fail:I
.field public static final ic_plugin_auth_desktop:I
.field public static final ic_plugin_auth_dingtalk_logo:I
.field public static final ic_plugin_auth_link:I
.field public static final ic_plugin_auth_link_connector:I
.field public static final ic_plugin_auth_tencent_docs_logo:I
.field public static final ic_plugin_auth_trae_logo:I
.field public static final ic_plugin_auth_wecom_logo:I
.field public static final ic_plugin_authorized:I
.field public static final ic_plugin_default:I
.field public static final ic_radio_selected:I
.field public static final ic_radio_unselected:I
.field public static final ic_remote:I
.field public static final ic_repo_checkmark_circle_disable:I
.field public static final ic_repo_checkmark_circle_enable:I
.field public static final ic_repo_confirm:I
.field public static final ic_save_poster:I
.field public static final ic_search:I
.field public static final ic_search_clear:I
.field public static final ic_share:I
.field public static final ic_share_closed:I
.field public static final ic_share_stop_copy:I
.field public static final ic_skill:I
.field public static final ic_skill_list:I
.field public static final ic_starbucks:I
.field public static final ic_starbucks_share_link:I
.field public static final ic_starbucks_share_save:I
.field public static final ic_starbucks_share_wechat:I
.field public static final ic_startbucks_share_wechat:I
.field public static final ic_tag_code:I
.field public static final ic_tag_file:I
.field public static final ic_tag_folder:I
.field public static final ic_tag_plan:I
.field public static final ic_tag_pr:I
.field public static final ic_tag_slash:I
.field public static final ic_tag_terminal:I
.field public static final ic_title_bar_chat:I
.field public static final ic_title_bar_more:I
.field public static final ic_tool_brain:I
.field public static final ic_tool_chevron_right:I
.field public static final ic_tool_mcp:I
.field public static final ic_tool_search:I
.field public static final ic_tool_terminal:I
.field public static final ic_tool_web:I
.field public static final ic_toolcall_skill:I
.field public static final ic_upload_file_default:I
.field public static final ic_welcome_add:I
.field public static final ic_welcome_back:I
.field public static final ic_welcome_chat_group:I
.field public static final ic_welcome_cloud:I
.field public static final ic_welcome_microphone:I
.field public static final ic_work_folder:I
.field public static final icon_16_chat_new:I
.field public static final icon_16_checkmark:I
.field public static final icon_16_checkmark_circle_filled:I
.field public static final icon_16_more:I
.field public static final iconchevronleftmedium:I
.field public static final img_device_activate:I
.field public static final img_device_manager_pair:I
.field public static final img_starbuck:I
.field public static final in_process:I
.field public static final info_filled:I
.field public static final info_filled_blue:I
.field public static final intro_btn_dark:I
.field public static final intro_icon_voice_phone:I
.field public static final intro_icon_voice_wave:I
.field public static final logo:I
.field public static final markdown:I
.field public static final microphone:I
.field public static final microphone_1:I
.field public static final plus:I
.field public static final python:I
.field public static final question:I
.field public static final radio_selected:I
.field public static final radio_unselected:I
.field public static final speaker:I
.field public static final status_loading:I
.field public static final status_loading_1:I
.field public static final status_loading_2:I
.field public static final status_loading_3:I
.field public static final status_loading_4:I
.field public static final status_loading_5:I
.field public static final status_loading_6:I
.field public static final status_loading_7:I
.field public static final status_loading_anim:I
.field public static final text_edit:I
.field public static final todo:I
.field public static final trae_bg_add_device_btn:I
.field public static final trae_bg_add_device_secondary:I
.field public static final trae_bg_artifact_loading_gradient:I
.field public static final trae_bg_assistant_icon_btn:I
.field public static final trae_bg_audio_visualizer_cancel:I
.field public static final trae_bg_audio_visualizer_normal:I
.field public static final trae_bg_avatar_fast_tooltip:I
.field public static final trae_bg_bottom_sheet:I
.field public static final trae_bg_bottom_sheet_handle:I
.field public static final trae_bg_bottom_sheet_rounded:I
.field public static final trae_bg_brainstorm_ai_bubble:I
.field public static final trae_bg_brainstorm_attachment_card:I
.field public static final trae_bg_brainstorm_attachment_close:I
.field public static final trae_bg_brainstorm_avatar_circle:I
.field public static final trae_bg_brainstorm_avatar_glow:I
.field public static final trae_bg_brainstorm_bottom_sheet:I
.field public static final trae_bg_brainstorm_capsule:I
.field public static final trae_bg_brainstorm_card_active:I
.field public static final trae_bg_brainstorm_circle_button_dark:I
.field public static final trae_bg_brainstorm_circle_button_gray:I
.field public static final trae_bg_brainstorm_circle_button_white:I
.field public static final trae_bg_brainstorm_close_button:I
.field public static final trae_bg_brainstorm_close_circle:I
.field public static final trae_bg_brainstorm_device_item_normal:I
.field public static final trae_bg_brainstorm_device_item_selected:I
.field public static final trae_bg_brainstorm_discuss_gradient:I
.field public static final trae_bg_brainstorm_drag_handle:I
.field public static final trae_bg_brainstorm_expand_button:I
.field public static final trae_bg_brainstorm_expand_button_ripple:I
.field public static final trae_bg_brainstorm_header_pill:I
.field public static final trae_bg_brainstorm_image_upload_overlay:I
.field public static final trae_bg_brainstorm_intro_avatar_ai:I
.field public static final trae_bg_brainstorm_intro_blur_circle:I
.field public static final trae_bg_brainstorm_intro_mic_circle:I
.field public static final trae_bg_brainstorm_intro_start_button:I
.field public static final trae_bg_brainstorm_intro_waveform_pill:I
.field public static final trae_bg_brainstorm_popup:I
.field public static final trae_bg_brainstorm_sheet_handle:I
.field public static final trae_bg_brainstorm_start_button:I
.field public static final trae_bg_brainstorm_subtask_badge:I
.field public static final trae_bg_brainstorm_subtitle_top_fade:I
.field public static final trae_bg_brainstorm_suggestion_card:I
.field public static final trae_bg_brainstorm_timeout_chip:I
.field public static final trae_bg_brainstorm_user_bubble:I
.field public static final trae_bg_brainstorm_user_card:I
.field public static final trae_bg_btn_confirm:I
.field public static final trae_bg_btn_grey_48:I
.field public static final trae_bg_btn_right_capsule:I
.field public static final trae_bg_chat_attachment_tag:I
.field public static final trae_bg_chat_bubble_received:I
.field public static final trae_bg_chat_bubble_sent:I
.field public static final trae_bg_chat_bubble_sent_pressed:I
.field public static final trae_bg_checkpoint_btn_danger:I
.field public static final trae_bg_checkpoint_btn_primary:I
.field public static final trae_bg_checkpoint_btn_secondary:I
.field public static final trae_bg_checkpoint_card:I
.field public static final trae_bg_checkpoint_checkbox_checked:I
.field public static final trae_bg_checkpoint_checkbox_unchecked:I
.field public static final trae_bg_checkpoint_close_btn:I
.field public static final trae_bg_checkpoint_drag_handle:I
.field public static final trae_bg_checkpoint_input:I
.field public static final trae_bg_checkpoint_option_index:I
.field public static final trae_bg_checkpoint_option_normal:I
.field public static final trae_bg_checkpoint_option_selected:I
.field public static final trae_bg_checkpoint_send_disabled:I
.field public static final trae_bg_checkpoint_subtitle_bottom_fade:I
.field public static final trae_bg_checkpoint_subtitle_top_fade:I
.field public static final trae_bg_circle_white_shadow:I
.field public static final trae_bg_cloud_btn:I
.field public static final trae_bg_cloud_btn_disabled:I
.field public static final trae_bg_connect_guide_image:I
.field public static final trae_bg_connect_guide_input:I
.field public static final trae_bg_connect_guide_sheet:I
.field public static final trae_bg_conversation_input:I
.field public static final trae_bg_device_activate_inner_box:I
.field public static final trae_bg_device_tips_close:I
.field public static final trae_bg_diff_title_btn:I
.field public static final trae_bg_dot_indicator:I
.field public static final trae_bg_drag_handle:I
.field public static final trae_bg_empty_icon:I
.field public static final trae_bg_error_emoji:I
.field public static final trae_bg_error_retry_btn:I
.field public static final trae_bg_express_pass_banner:I
.field public static final trae_bg_github_icon_container:I
.field public static final trae_bg_grabber:I
.field public static final trae_bg_header_gradient:I
.field public static final trae_bg_html_preview_error_icon_card:I
.field public static final trae_bg_html_preview_reload_button:I
.field public static final trae_bg_icon_btn_green:I
.field public static final trae_bg_icon_btn_grey:I
.field public static final trae_bg_icon_button:I
.field public static final trae_bg_image_placeholder:I
.field public static final trae_bg_input_action_btn:I
.field public static final trae_bg_input_action_btn_brand:I
.field public static final trae_bg_input_action_btn_with_inset:I
.field public static final trae_bg_input_attachment_ext_badge:I
.field public static final trae_bg_input_attachment_file:I
.field public static final trae_bg_input_attachment_remove:I
.field public static final trae_bg_input_bottom_layer:I
.field public static final trae_bg_input_top_layer:I
.field public static final trae_bg_invert_disabled_circle:I
.field public static final trae_bg_invert_enable_circle:I
.field public static final trae_bg_minimized_voice_bar:I
.field public static final trae_bg_model_chip:I
.field public static final trae_bg_model_discount_tag:I
.field public static final trae_bg_multi_image_preview_circle:I
.field public static final trae_bg_notify_file_chip:I
.field public static final trae_bg_pill_white_shadow:I
.field public static final trae_bg_plugin_auth_desktop_cancel_button:I
.field public static final trae_bg_plugin_auth_icon_card:I
.field public static final trae_bg_plugin_auth_qrcode_box:I
.field public static final trae_bg_plugin_auth_qrcode_card:I
.field public static final trae_bg_plugin_authorization_primary_button:I
.field public static final trae_bg_plugin_authorization_secondary_button:I
.field public static final trae_bg_product_type_ide:I
.field public static final trae_bg_product_type_work:I
.field public static final trae_bg_recording_complete_btn:I
.field public static final trae_bg_repo_search_input:I
.field public static final trae_bg_retry_button:I
.field public static final trae_bg_scroll_to_bottom:I
.field public static final trae_bg_search_input:I
.field public static final trae_bg_share_link_copied_btn:I
.field public static final trae_bg_share_link_generating_btn:I
.field public static final trae_bg_share_link_sheet:I
.field public static final trae_bg_share_link_stop_btn:I
.field public static final trae_bg_share_link_url_container:I
.field public static final trae_bg_solo_dialog_btn:I
.field public static final trae_bg_suggestion_chip:I
.field public static final trae_bg_suggestion_chip_image:I
.field public static final trae_bg_task_location_add_device:I
.field public static final trae_bg_task_location_item:I
.field public static final trae_bg_task_location_item_selected:I
.field public static final trae_bg_task_location_item_unselected:I
.field public static final trae_bg_task_location_status_offline:I
.field public static final trae_bg_task_location_status_online:I
.field public static final trae_bg_task_location_status_unpaired:I
.field public static final trae_bg_task_template_card:I
.field public static final trae_bg_title_bar_mark_gradient:I
.field public static final trae_bg_tool_badge_cancel:I
.field public static final trae_bg_tool_badge_warning:I
.field public static final trae_bg_trae_ide:I
.field public static final trae_bg_trae_work:I
.field public static final trae_bg_view_voice_history_btn:I
.field public static final trae_bg_voice_discussion_switch_dialog:I
.field public static final trae_bg_voice_discussion_switch_dialog_button:I
.field public static final trae_bg_voice_history_close:I
.field public static final trae_bg_voice_history_empty_icon:I
.field public static final trae_bg_voice_history_sheet:I
.field public static final trae_bg_voice_history_user_bubble:I
.field public static final trae_bg_welcome_composer_surface:I
.field public static final trae_bg_welcome_env_toggle:I
.field public static final trae_bg_welcome_green_cursor:I
.field public static final trae_bg_welcome_send_btn:I
.field public static final trae_bg_welcome_send_btn_inactive:I
.field public static final trae_bg_welcome_tooltip:I
.field public static final trae_bg_welcome_tooltip_arrow:I
.field public static final trae_connect_guide_ide_hero:I
.field public static final trae_connect_guide_work_hero:I
.field public static final trae_device_add_button_bg:I
.field public static final trae_device_back_button_bg:I
.field public static final trae_device_bg_radio_selected:I
.field public static final trae_device_bg_radio_selector:I
.field public static final trae_device_bg_radio_unselected:I
.field public static final trae_device_bg_status_chip_offline:I
.field public static final trae_device_bg_status_chip_online:I
.field public static final trae_device_item_icon_bg:I
.field public static final trae_device_target_ide_icon:I
.field public static final trae_device_target_work_icon:I
.field public static final trae_ic_artifact_loading_spinner:I
.field public static final trae_ic_avatar_coder:I
.field public static final trae_ic_avatar_mtc:I
.field public static final trae_ic_avatar_non_ide:I
.field public static final trae_ic_brainstorm_attach:I
.field public static final trae_ic_brainstorm_attach_close_small:I
.field public static final trae_ic_brainstorm_attach_type_pdf:I
.field public static final trae_ic_brainstorm_attachment_status_action:I
.field public static final trae_ic_brainstorm_chat_group:I
.field public static final trae_ic_brainstorm_chat_group_1:I
.field public static final trae_ic_brainstorm_check:I
.field public static final trae_ic_brainstorm_checkbox_checked:I
.field public static final trae_ic_brainstorm_checkbox_unchecked:I
.field public static final trae_ic_brainstorm_close:I
.field public static final trae_ic_brainstorm_fullscreen:I
.field public static final trae_ic_brainstorm_headphone:I
.field public static final trae_ic_brainstorm_history:I
.field public static final trae_ic_brainstorm_intro_ai_symbol:I
.field public static final trae_ic_brainstorm_intro_line_left:I
.field public static final trae_ic_brainstorm_intro_line_right:I
.field public static final trae_ic_brainstorm_intro_mic:I
.field public static final trae_ic_brainstorm_intro_phone_mockup:I
.field public static final trae_ic_brainstorm_logo:I
.field public static final trae_ic_brainstorm_maximize:I
.field public static final trae_ic_brainstorm_mic:I
.field public static final trae_ic_brainstorm_mic_bubble:I
.field public static final trae_ic_brainstorm_mic_off:I
.field public static final trae_ic_brainstorm_minimize:I
.field public static final trae_ic_brainstorm_more:I
.field public static final trae_ic_brainstorm_scroll_down:I
.field public static final trae_ic_brainstorm_speaker:I
.field public static final trae_ic_brainstorm_speaker_off:I
.field public static final trae_ic_brainstorm_subtask_done:I
.field public static final trae_ic_brainstorm_subtask_failed:I
.field public static final trae_ic_brainstorm_subtask_loading:I
.field public static final trae_ic_brainstorm_subtitle:I
.field public static final trae_ic_brainstorm_subtitle_active:I
.field public static final trae_ic_brainstorm_subtitle_off:I
.field public static final trae_ic_brainstorm_subtitle_on:I
.field public static final trae_ic_brainstorm_user_avatar:I
.field public static final trae_ic_chain_link:I
.field public static final trae_ic_chain_unlink:I
.field public static final trae_ic_checkpoint_back:I
.field public static final trae_ic_checkpoint_check:I
.field public static final trae_ic_checkpoint_close:I
.field public static final trae_ic_checkpoint_confirm:I
.field public static final trae_ic_checkpoint_edit:I
.field public static final trae_ic_checkpoint_header_next:I
.field public static final trae_ic_checkpoint_header_prev:I
.field public static final trae_ic_checkpoint_send:I
.field public static final trae_ic_checkpoint_single_check:I
.field public static final trae_ic_chevron_fold:I
.field public static final trae_ic_close_white:I
.field public static final trae_ic_connect_guide_inactive:I
.field public static final trae_ic_connect_guide_share:I
.field public static final trae_ic_connect_guide_waiting:I
.field public static final trae_ic_copy:I
.field public static final trae_ic_copy_checkmark:I
.field public static final trae_ic_figma_check:I
.field public static final trae_ic_figma_close:I
.field public static final trae_ic_file_document_16:I
.field public static final trae_ic_github_empty:I
.field public static final trae_ic_html_preview_file_document:I
.field public static final trae_ic_input_attachment_close:I
.field public static final trae_ic_input_attachment_retry:I
.field public static final trae_ic_minus_circle:I
.field public static final trae_ic_more:I
.field public static final trae_ic_notify_markdown_file:I
.field public static final trae_ic_product_type_ide:I
.field public static final trae_ic_product_type_work:I
.field public static final trae_ic_radio_checkmark_circle_filled:I
.field public static final trae_ic_regenerate:I
.field public static final trae_ic_report:I
.field public static final trae_ic_retry:I
.field public static final trae_ic_select_text:I
.field public static final trae_ic_thumbs_down:I
.field public static final trae_ic_thumbs_down_filled:I
.field public static final trae_ic_thumbs_up:I
.field public static final trae_ic_thumbs_up_filled:I
.field public static final trae_ic_title_bar_share:I
.field public static final trae_ic_tooltip_arrow_down:I
.field public static final trae_ic_voice_file_design:I
.field public static final trae_ic_voice_file_diff:I
.field public static final trae_ic_voice_file_excel:I
.field public static final trae_ic_voice_file_folder:I
.field public static final trae_ic_voice_file_generic:I
.field public static final trae_ic_voice_file_html:I
.field public static final trae_ic_voice_file_jpg:I
.field public static final trae_ic_voice_file_json:I
.field public static final trae_ic_voice_file_markdown:I
.field public static final trae_ic_voice_file_mp3:I
.field public static final trae_ic_voice_file_mp4:I
.field public static final trae_ic_voice_file_pdf:I
.field public static final trae_ic_voice_file_png:I
.field public static final trae_ic_voice_file_ppt:I
.field public static final trae_ic_voice_file_skill:I
.field public static final trae_ic_voice_file_text:I
.field public static final trae_ic_voice_file_word:I
.field public static final trae_ic_voice_file_zip:I
.field public static final trae_ic_voice_history_close:I
.field public static final trae_ic_voice_history_empty_document:I
.field public static final trae_img_billing_upgrade_prompt_hero:I
.field public static final trae_img_device_manager_tips:I
.field public static final trae_img_glass:I
.field public static final trae_img_new_feature_prompt_ide_hero:I
.field public static final trae_img_new_feature_prompt_ide_hero_2026q3:I
.field public static final trae_img_new_feature_prompt_work_hero:I
.field public static final trae_img_new_feature_prompt_work_hero_2026q3:I
.field public static final trae_media_choose_bg_duration:I
.field public static final trae_media_choose_bg_select_circle:I
.field public static final trae_media_choose_bg_send:I
.field public static final trae_media_choose_ic_back:I
.field public static final trae_media_choose_ic_camera:I
.field public static final trae_selector_document_radio:I
.field public static final trash:I
.field public static final user_remove:I
.field public static final warning:I
.field public static final warning_circle:I
.field public static final warning_filled:I
.field public static final warning_filled_red:I
.field public static final warning_filled_yellow:I
.field public static final waveform:I


.method private constructor <init>()void
    .registers 1
    # ins_size=1
    invoke-direct v0, Ljava/lang/Object;-><init>()V
    return-void 
.end method
