# Decompiled TRAE business class
# Source DEX: classes5.dex
.class public final Lcom/bytedance/trae/conversation/R$id;
.super Ljava/lang/Object;

.field public static final action_group:I
.field public static final action_pill:I
.field public static final ai_display_switcher:I
.field public static final ai_subtitle_container:I
.field public static final avatar_glow:I
.field public static final bottom_action_container:I
.field public static final bottom_bar:I
.field public static final bottom_contextual_bar:I
.field public static final bottom_prompt_spacer:I
.field public static final bottom_sheet_container:I
.field public static final brainstorm_fragment_container:I
.field public static final btn_add_device:I
.field public static final btn_add_folder:I
.field public static final btn_allow:I
.field public static final btn_attach:I
.field public static final btn_back:I
.field public static final btn_branch:I
.field public static final btn_camera:I
.field public static final btn_cancel:I
.field public static final btn_chat_new:I
.field public static final btn_close:I
.field public static final btn_close_summary:I
.field public static final btn_confirm:I
.field public static final btn_connect:I
.field public static final btn_copied:I
.field public static final btn_copy_link:I
.field public static final btn_custom_send:I
.field public static final btn_desktop_cancel:I
.field public static final btn_device:I
.field public static final btn_download:I
.field public static final btn_express_pass:I
.field public static final btn_extend:I
.field public static final btn_files:I
.field public static final btn_generate_container:I
.field public static final btn_generate_link:I
.field public static final btn_github:I
.field public static final btn_go_to_github:I
.field public static final btn_header_next:I
.field public static final btn_header_prev:I
.field public static final btn_hold_to_talk:I
.field public static final btn_left:I
.field public static final btn_main_download:I
.field public static final btn_maximize:I
.field public static final btn_mic:I
.field public static final btn_microphone:I
.field public static final btn_minimize:I
.field public static final btn_next:I
.field public static final btn_ok:I
.field public static final btn_operation_icon:I
.field public static final btn_pause:I
.field public static final btn_photo:I
.field public static final btn_plugin_auth_desktop_cancel:I
.field public static final btn_plugin_authorization_authorize:I
.field public static final btn_plugin_authorization_cancel:I
.field public static final btn_plugins:I
.field public static final btn_plus:I
.field public static final btn_prev:I
.field public static final btn_preview:I
.field public static final btn_remove:I
.field public static final btn_retry:I
.field public static final btn_retry_load:I
.field public static final btn_right:I
.field public static final btn_scroll_to_bottom:I
.field public static final btn_select_folder:I
.field public static final btn_select_other_folder:I
.field public static final btn_send:I
.field public static final btn_send_text:I
.field public static final btn_share:I
.field public static final btn_skills:I
.field public static final btn_start:I
.field public static final btn_start_agent:I
.field public static final btn_stop_sharing:I
.field public static final btn_subtitle_toggle:I
.field public static final btn_use_now:I
.field public static final card_attachment:I
.field public static final card_bg:I
.field public static final card_container:I
.field public static final card_file_cell:I
.field public static final card_image_cell:I
.field public static final cb_origin:I
.field public static final chat_mode_container:I
.field public static final checkbox_container:I
.field public static final checkpoint_overlay_container:I
.field public static final chip_content_creation:I
.field public static final chip_data_mining:I
.field public static final chip_web_reading:I
.field public static final container:I
.field public static final container_inner:I
.field public static final container_metadata:I
.field public static final container_task_header:I
.field public static final content_container:I
.field public static final content_switcher:I
.field public static final desc_container:I
.field public static final detail_fragment_container:I
.field public static final device_flow_content:I
.field public static final device_flow_root:I
.field public static final device_list_container:I
.field public static final directory_content_container:I
.field public static final divider:I
.field public static final divider_delete:I
.field public static final divider_revert:I
.field public static final dots_bg:I
.field public static final download_status_tile:I
.field public static final drag_handle:I
.field public static final empty_state_container:I
.field public static final error_container:I
.field public static final et_custom_answer:I
.field public static final et_folder_name:I
.field public static final et_input:I
.field public static final et_search:I
.field public static final express_pass_close:I
.field public static final file_info_overlay:I
.field public static final fl_agent_header:I
.field public static final fl_content:I
.field public static final fl_text_container:I
.field public static final footer_container:I
.field public static final fragment_container:I
.field public static final full_input_container:I
.field public static final greeting_container:I
.field public static final guideline_sphere_top:I
.field public static final header:I
.field public static final header_nav_group:I
.field public static final im_artifact_interceptor:I
.field public static final image_container:I
.field public static final img_im_artifact:I
.field public static final img_select_branch:I
.field public static final indicator:I
.field public static final input_bottom:I
.field public static final input_fragment_container:I
.field public static final item_ide:I
.field public static final item_work:I
.field public static final iv_arrow:I
.field public static final iv_attach_close:I
.field public static final iv_attach_preview:I
.field public static final iv_attach_type_icon:I
.field public static final iv_attachment:I
.field public static final iv_avatar:I
.field public static final iv_avatar_fast:I
.field public static final iv_avatar_icon:I
.field public static final iv_camera:I
.field public static final iv_cell_close:I
.field public static final iv_cell_preview:I
.field public static final iv_chat_icon:I
.field public static final iv_check:I
.field public static final iv_checkbox:I
.field public static final iv_chevron_right:I
.field public static final iv_close:I
.field public static final iv_cloud_icon:I
.field public static final iv_connect_guide_image:I
.field public static final iv_content_creation:I
.field public static final iv_custom_edit:I
.field public static final iv_custom_send:I
.field public static final iv_data_mining:I
.field public static final iv_desktop_provider_icon:I
.field public static final iv_device_activate:I
.field public static final iv_device_badge:I
.field public static final iv_device_icon:I
.field public static final iv_expand:I
.field public static final iv_express_pass_benefit_close:I
.field public static final iv_express_pass_benefit_icon:I
.field public static final iv_file_close:I
.field public static final iv_file_icon:I
.field public static final iv_file_type_icon:I
.field public static final iv_header_next:I
.field public static final iv_header_prev:I
.field public static final iv_icon:I
.field public static final iv_icon_editing:I
.field public static final iv_image:I
.field public static final iv_indicator:I
.field public static final iv_loading:I
.field public static final iv_menu_pin:I
.field public static final iv_option_single_check:I
.field public static final iv_pager_image:I
.field public static final iv_phone_mockup:I
.field public static final iv_plugin_auth_link_icon:I
.field public static final iv_plugin_auth_provider_icon:I
.field public static final iv_plugin_auth_qrcode_provider_icon:I
.field public static final iv_plugin_auth_trae_icon:I
.field public static final iv_plugin_authorization_qrcode:I
.field public static final iv_plugin_authorization_success_icon:I
.field public static final iv_plugin_icon:I
.field public static final iv_preview:I
.field public static final iv_prompt_image:I
.field public static final iv_provider_icon:I
.field public static final iv_qrcode:I
.field public static final iv_radio:I
.field public static final iv_repo_icon:I
.field public static final iv_search_clear:I
.field public static final iv_search_icon:I
.field public static final iv_step1_status:I
.field public static final iv_step2_status:I
.field public static final iv_subtask_loading:I
.field public static final iv_subtask_status_icon:I
.field public static final iv_target_icon:I
.field public static final iv_thumb:I
.field public static final iv_voice_history_close:I
.field public static final iv_web_reading:I
.field public static final layout_container:I
.field public static final layout_content:I
.field public static final layout_desktop_content:I
.field public static final layout_empty:I
.field public static final layout_empty_state:I
.field public static final layout_error:I
.field public static final layout_load_error:I
.field public static final layout_network_error:I
.field public static final layout_plugin_authorization_actions:I
.field public static final layout_plugin_authorization_desktop_redirect:I
.field public static final layout_plugin_authorization_qrcode:I
.field public static final layout_plugin_authorization_success:I
.field public static final layout_qr_icon_row:I
.field public static final layout_qrcode_content:I
.field public static final ll_agent_header:I
.field public static final ll_attach_file_content:I
.field public static final ll_attach_name_row:I
.field public static final ll_body:I
.field public static final ll_cloud:I
.field public static final ll_cloud_content:I
.field public static final ll_container:I
.field public static final ll_content:I
.field public static final ll_device_folder_bar:I
.field public static final ll_express_pass_benefit:I
.field public static final ll_file_content:I
.field public static final ll_generating:I
.field public static final ll_header:I
.field public static final ll_indent:I
.field public static final ll_menu_container:I
.field public static final ll_message_container:I
.field public static final ll_product_type:I
.field public static final ll_suggestion_chips:I
.field public static final ll_title_container:I
.field public static final ll_todo_list:I
.field public static final ll_tool_list:I
.field public static final ll_trailing_actions:I
.field public static final ll_voice_history_empty:I
.field public static final loading_container:I
.field public static final loading_root:I
.field public static final main_input_area:I
.field public static final main_waveform:I
.field public static final menu_artifact:I
.field public static final menu_copy:I
.field public static final menu_delete:I
.field public static final menu_divider_artifact:I
.field public static final menu_divider_pin:I
.field public static final menu_pin:I
.field public static final menu_rename:I
.field public static final menu_revert:I
.field public static final minimized_voice_bar:I
.field public static final mockup_container:I
.field public static final model_selector:I
.field public static final normal_content:I
.field public static final notify_file_chip:I
.field public static final option_root:I
.field public static final options_grid:I
.field public static final overlay_attach_failed:I
.field public static final overlay_attach_loading:I
.field public static final overlay_cell_failed:I
.field public static final overlay_cell_loading:I
.field public static final overlay_failed:I
.field public static final overlay_file_failed:I
.field public static final overlay_file_loading:I
.field public static final overlay_loading:I
.field public static final pager:I
.field public static final partial_permission_notice:I
.field public static final pb_loading_more:I
.field public static final pb_plugin_authorization_loading:I
.field public static final pb_plugin_authorization_qrcode_loading:I
.field public static final pb_qrcode_loading:I
.field public static final pb_search_loading:I
.field public static final progress_bar:I
.field public static final progress_creating:I
.field public static final progress_loading:I
.field public static final progress_newer_page_loading:I
.field public static final progress_older_page_loading:I
.field public static final radio_project:I
.field public static final rb_select:I
.field public static final recycler_view:I
.field public static final rv:I
.field public static final rv_ai_subtitle:I
.field public static final rv_artifact_list:I
.field public static final rv_attachments:I
.field public static final rv_branches:I
.field public static final rv_clis:I
.field public static final rv_code_changed_list:I
.field public static final rv_devices:I
.field public static final rv_directory:I
.field public static final rv_documents:I
.field public static final rv_file_list:I
.field public static final rv_files:I
.field public static final rv_image_row:I
.field public static final rv_images:I
.field public static final rv_messages:I
.field public static final rv_options:I
.field public static final rv_projects:I
.field public static final rv_recent_folders:I
.field public static final rv_repositories:I
.field public static final rv_subtitle:I
.field public static final rv_task_templates:I
.field public static final rv_tool_list:I
.field public static final rv_voice_history:I
.field public static final scroll_markdown:I
.field public static final scroll_txt:I
.field public static final search_container:I
.field public static final selection_container:I
.field public static final sending:I
.field public static final share_link_desc:I
.field public static final space_pill_gap:I
.field public static final spacer_camera_photo:I
.field public static final spacer_photo_files:I
.field public static final sphere_area:I
.field public static final status_error:I
.field public static final status_error_desc:I
.field public static final step1_card:I
.field public static final step2_card:I
.field public static final subtask_badge_container:I
.field public static final subtitle_bg:I
.field public static final subtitle_bottom_fade:I
.field public static final subtitle_mode_container:I
.field public static final subtitle_top_fade:I
.field public static final subtitle_top_gradient:I
.field public static final subtitle_viewport:I
.field public static final success_container:I
.field public static final sv_text_content:I
.field public static final tag_block_class:I
.field public static final tag_on_content_changed:I
.field public static final tag_on_pure_show_widget_inline_view_created:I
.field public static final tag_sub_agent_group_manager:I
.field public static final tag_summary_tracking_id:I
.field public static final tag_toolcall_group_key:I
.field public static final tag_typewriter:I
.field public static final test_frame:I
.field public static final text_container:I
.field public static final thinking_dots:I
.field public static final timer_container:I
.field public static final title_bar:I
.field public static final title_bar_mark:I
.field public static final title_scroll_view:I
.field public static final toolbar:I
.field public static final top_bar:I
.field public static final top_prompt_spacer:I
.field public static final trae_media_choose_container:I
.field public static final trae_tag_todo_group_view_manager:I
.field public static final trae_url:I
.field public static final tv_action_items:I
.field public static final tv_agent_desc:I
.field public static final tv_agent_icon:I
.field public static final tv_agent_name:I
.field public static final tv_ai_status:I
.field public static final tv_ai_subtitle_line:I
.field public static final tv_arrow:I
.field public static final tv_attach_name:I
.field public static final tv_attach_status:I
.field public static final tv_avatar_name:I
.field public static final tv_badge:I
.field public static final tv_bottom_status:I
.field public static final tv_branch_name:I
.field public static final tv_cli_name:I
.field public static final tv_cli_status:I
.field public static final tv_cloud_dot:I
.field public static final tv_cloud_name:I
.field public static final tv_cloud_status:I
.field public static final tv_cloud_text:I
.field public static final tv_content:I
.field public static final tv_content_creation:I
.field public static final tv_data_mining:I
.field public static final tv_desc:I
.field public static final tv_desc_line1:I
.field public static final tv_desc_line2:I
.field public static final tv_desktop_message:I
.field public static final tv_desktop_shimmer:I
.field public static final tv_detail:I
.field public static final tv_device_activate_description:I
.field public static final tv_device_activate_title:I
.field public static final tv_device_name:I
.field public static final tv_dialog_title:I
.field public static final tv_duration:I
.field public static final tv_empty:I
.field public static final tv_empty_hint:I
.field public static final tv_empty_state:I
.field public static final tv_error_content:I
.field public static final tv_error_subtitle:I
.field public static final tv_error_title:I
.field public static final tv_express_pass_benefit:I
.field public static final tv_express_pass_subtitle:I
.field public static final tv_express_pass_title:I
.field public static final tv_ext_badge:I
.field public static final tv_file_action:I
.field public static final tv_file_ext:I
.field public static final tv_file_name:I
.field public static final tv_file_path:I
.field public static final tv_file_status:I
.field public static final tv_filename:I
.field public static final tv_folder_name:I
.field public static final tv_footer:I
.field public static final tv_footer_hint:I
.field public static final tv_footer_shimmer:I
.field public static final tv_full_text:I
.field public static final tv_generated_by_ai:I
.field public static final tv_hold_to_talk:I
.field public static final tv_icon:I
.field public static final tv_icon_emoji:I
.field public static final tv_indicator:I
.field public static final tv_key_points:I
.field public static final tv_label:I
.field public static final tv_markdown:I
.field public static final tv_menu_pin:I
.field public static final tv_message:I
.field public static final tv_message_content:I
.field public static final tv_model_name:I
.field public static final tv_name:I
.field public static final tv_option_index:I
.field public static final tv_order:I
.field public static final tv_plugin_auth_desktop_footer:I
.field public static final tv_plugin_auth_desktop_message:I
.field public static final tv_plugin_authorization_body:I
.field public static final tv_plugin_authorization_qrcode_desc:I
.field public static final tv_plugin_authorization_qrcode_footer:I
.field public static final tv_plugin_authorization_qrcode_status:I
.field public static final tv_plugin_authorization_success_label:I
.field public static final tv_plugin_authorization_success_name:I
.field public static final tv_plugin_name:I
.field public static final tv_product_type:I
.field public static final tv_progress:I
.field public static final tv_project_name:I
.field public static final tv_project_path:I
.field public static final tv_prompt_message:I
.field public static final tv_prompt_title:I
.field public static final tv_qr_shimmer:I
.field public static final tv_question:I
.field public static final tv_repo_name:I
.field public static final tv_search_empty:I
.field public static final tv_section_actions:I
.field public static final tv_section_key_points:I
.field public static final tv_share_url:I
.field public static final tv_show_more:I
.field public static final tv_skill_name:I
.field public static final tv_status:I
.field public static final tv_step1:I
.field public static final tv_step1_status:I
.field public static final tv_step2:I
.field public static final tv_step2_status:I
.field public static final tv_subtask_status_text:I
.field public static final tv_subtitle:I
.field public static final tv_subtitle_content:I
.field public static final tv_subtitle_empty_hint:I
.field public static final tv_summary:I
.field public static final tv_tag:I
.field public static final tv_target_subtitle:I
.field public static final tv_target_title:I
.field public static final tv_task_name:I
.field public static final tv_time:I
.field public static final tv_timeout_chip:I
.field public static final tv_timer:I
.field public static final tv_title:I
.field public static final tv_todo_title:I
.field public static final tv_toggle_text:I
.field public static final tv_tooltip_text:I
.field public static final tv_txt:I
.field public static final tv_voice_history_content:I
.field public static final tv_voice_history_status:I
.field public static final tv_voice_history_title:I
.field public static final tv_web_reading:I
.field public static final tv_welcome_subtitle:I
.field public static final tv_welcome_title:I
.field public static final upgrade_reminder_card:I
.field public static final v_badge:I
.field public static final v_gradient_mask:I
.field public static final v_mask:I
.field public static final v_vertical_line:I
.field public static final video_view:I
.field public static final view_indent:I
.field public static final view_indent_editing:I
.field public static final view_pager:I
.field public static final voice_recording_overlay:I
.field public static final vs_task_templates:I
.field public static final waveform_view:I
.field public static final webview:I
.field public static final webview_diff:I
.field public static final webview_sphere:I
.field public static final welcome_fragment_container:I


.method private constructor <init>()void
    .registers 1
    # ins_size=1
    invoke-direct v0, Ljava/lang/Object;-><init>()V
    return-void 
.end method
