# Decompiled TRAE business class
# Source DEX: classes5.dex
.class public final Lcom/bytedance/trae/conversation/R$string;
.super Ljava/lang/Object;

.field public static final imkit_model_builtin_models:I
.field public static final imkit_model_custom_models:I
.field public static final imkit_model_discount_rate_format:I
.field public static final imkit_model_list_load_failed:I
.field public static final imkit_model_selection_auto:I
.field public static final imkit_model_title:I
.field public static final solo_welcome_greeting:I
.field public static final solo_welcome_greeting_code:I
.field public static final solo_welcome_greeting_default_name:I
.field public static final solo_welcome_subtitle:I
.field public static final trae_agent_review_check_pr:I
.field public static final trae_agent_review_create_pr:I
.field public static final trae_agent_review_desc_resolve:I
.field public static final trae_agent_review_desc_review:I
.field public static final trae_ai_data_notice_message:I
.field public static final trae_ai_data_notice_message_cn:I
.field public static final trae_ai_data_notice_ok:I
.field public static final trae_ai_data_notice_privacy_policy:I
.field public static final trae_ai_data_notice_privacy_policy_cn:I
.field public static final trae_ai_data_notice_title:I
.field public static final trae_artifact_loading:I
.field public static final trae_billing_upgrade_prompt_message:I
.field public static final trae_billing_upgrade_prompt_start:I
.field public static final trae_billing_upgrade_prompt_title:I
.field public static final trae_brainstorm_ai_thinking:I
.field public static final trae_brainstorm_attach:I
.field public static final trae_brainstorm_attach_cancelled:I
.field public static final trae_brainstorm_attach_close:I
.field public static final trae_brainstorm_attach_failed_retry:I
.field public static final trae_brainstorm_attach_in_flight_busy:I
.field public static final trae_brainstorm_attach_proxy_not_ready:I
.field public static final trae_brainstorm_attach_resend:I
.field public static final trae_brainstorm_attach_too_large:I
.field public static final trae_brainstorm_attach_total_too_large:I
.field public static final trae_brainstorm_attach_type_unsupported:I
.field public static final trae_brainstorm_attach_uploading_no_size:I
.field public static final trae_brainstorm_attach_uploading_progress:I
.field public static final trae_brainstorm_bottom_status_answering:I
.field public static final trae_brainstorm_bottom_status_listening:I
.field public static final trae_brainstorm_bottom_status_prompt:I
.field public static final trae_brainstorm_bottom_status_task_done:I
.field public static final trae_brainstorm_bottom_status_task_running:I
.field public static final trae_brainstorm_bottom_status_task_running_long:I
.field public static final trae_brainstorm_bottom_status_thinking:I
.field public static final trae_brainstorm_change_device:I
.field public static final trae_brainstorm_confirm:I
.field public static final trae_brainstorm_desktop_upgrade_required:I
.field public static final trae_brainstorm_device_bluetooth:I
.field public static final trae_brainstorm_device_earpiece:I
.field public static final trae_brainstorm_device_speaker:I
.field public static final trae_brainstorm_device_wired_headset:I
.field public static final trae_brainstorm_discussion_results:I
.field public static final trae_brainstorm_empty_summary_toast:I
.field public static final trae_brainstorm_end:I
.field public static final trae_brainstorm_end_session:I
.field public static final trae_brainstorm_exception_low_volume:I
.field public static final trae_brainstorm_exception_mic_permission:I
.field public static final trae_brainstorm_exception_output_volume_muted:I
.field public static final trae_brainstorm_exception_weak_network:I
.field public static final trae_brainstorm_exit_confirm_continue:I
.field public static final trae_brainstorm_exit_confirm_discard:I
.field public static final trae_brainstorm_exit_confirm_message:I
.field public static final trae_brainstorm_exit_confirm_title:I
.field public static final trae_brainstorm_hint_listening:I
.field public static final trae_brainstorm_interrupted:I
.field public static final trae_brainstorm_intro_desc:I
.field public static final trae_brainstorm_intro_desc_line1:I
.field public static final trae_brainstorm_intro_desc_line2:I
.field public static final trae_brainstorm_intro_footer:I
.field public static final trae_brainstorm_intro_title:I
.field public static final trae_brainstorm_listening:I
.field public static final trae_brainstorm_mic_off:I
.field public static final trae_brainstorm_mic_on:I
.field public static final trae_brainstorm_mic_permission_denied:I
.field public static final trae_brainstorm_speaker_off:I
.field public static final trae_brainstorm_speaker_on:I
.field public static final trae_brainstorm_sphere_welcome:I
.field public static final trae_brainstorm_start:I
.field public static final trae_brainstorm_subtask_done:I
.field public static final trae_brainstorm_subtask_failed:I
.field public static final trae_brainstorm_subtask_interrupted:I
.field public static final trae_brainstorm_subtask_running:I
.field public static final trae_brainstorm_subtask_running_long:I
.field public static final trae_brainstorm_subtitle_empty_hint:I
.field public static final trae_brainstorm_suggestion_1:I
.field public static final trae_brainstorm_suggestion_2:I
.field public static final trae_brainstorm_suggestion_3:I
.field public static final trae_brainstorm_summary_action_prefix:I
.field public static final trae_brainstorm_summary_actions:I
.field public static final trae_brainstorm_summary_bullet_prefix:I
.field public static final trae_brainstorm_summary_close:I
.field public static final trae_brainstorm_summary_key_points:I
.field public static final trae_brainstorm_summary_query:I
.field public static final trae_brainstorm_switch_session_confirm_message:I
.field public static final trae_brainstorm_switch_session_confirm_title:I
.field public static final trae_brainstorm_switch_session_continue:I
.field public static final trae_brainstorm_switch_session_exit:I
.field public static final trae_brainstorm_switched_to_device:I
.field public static final trae_brainstorm_test_mic:I
.field public static final trae_brainstorm_test_mic_stop:I
.field public static final trae_brainstorm_test_sound:I
.field public static final trae_brainstorm_test_sound_playing:I
.field public static final trae_brainstorm_timeout_ending:I
.field public static final trae_brainstorm_timeout_minutes:I
.field public static final trae_brainstorm_timeout_seconds:I
.field public static final trae_brainstorm_view_voice_history:I
.field public static final trae_brainstorm_voice_error_minimize_refused:I
.field public static final trae_brainstorm_voice_error_rtc:I
.field public static final trae_brainstorm_voice_error_start:I
.field public static final trae_brainstorm_voice_history_empty:I
.field public static final trae_brainstorm_voice_history_error:I
.field public static final trae_brainstorm_voice_history_loading:I
.field public static final trae_brainstorm_voice_history_role_assistant:I
.field public static final trae_brainstorm_voice_history_role_user:I
.field public static final trae_brainstorm_voice_history_title:I
.field public static final trae_brainstorm_voice_notification_active:I
.field public static final trae_brainstorm_voice_notification_channel:I
.field public static final trae_brainstorm_voice_notification_muted:I
.field public static final trae_brainstorm_voice_summary_loading:I
.field public static final trae_chat_agent_default_name:I
.field public static final trae_chat_append_interjected_status:I
.field public static final trae_chat_artifact_code_files:I
.field public static final trae_chat_artifact_files_changed:I
.field public static final trae_chat_artifact_merge_conflict_badge:I
.field public static final trae_chat_artifact_merge_subtitle:I
.field public static final trae_chat_artifact_merge_subtitle_conflict:I
.field public static final trae_chat_artifact_merge_title:I
.field public static final trae_chat_artifact_preview_failed:I
.field public static final trae_chat_artifact_preview_opened:I
.field public static final trae_chat_artifact_preview_opening:I
.field public static final trae_chat_artifact_preview_web:I
.field public static final trae_chat_artifacts_subtitle:I
.field public static final trae_chat_artifacts_title:I
.field public static final trae_chat_attachment_attachment:I
.field public static final trae_chat_attachment_code:I
.field public static final trae_chat_attachment_doc:I
.field public static final trae_chat_attachment_file:I
.field public static final trae_chat_attachment_folder:I
.field public static final trae_chat_attachment_image:I
.field public static final trae_chat_attachment_terminal:I
.field public static final trae_chat_attachment_web:I
.field public static final trae_chat_attachment_web_search:I
.field public static final trae_chat_browser_actions_count:I
.field public static final trae_chat_created_todos:I
.field public static final trae_chat_error_code_format:I
.field public static final trae_chat_error_default:I
.field public static final trae_chat_error_format:I
.field public static final trae_chat_manual_stop_status:I
.field public static final trae_chat_other_tools:I
.field public static final trae_chat_process_detail_title:I
.field public static final trae_chat_queue_alert_body:I
.field public static final trae_chat_queue_alert_title:I
.field public static final trae_chat_queue_refunded:I
.field public static final trae_chat_read_files:I
.field public static final trae_chat_ref_count:I
.field public static final trae_chat_ref_docs:I
.field public static final trae_chat_ref_document:I
.field public static final trae_chat_ref_file:I
.field public static final trae_chat_ref_read_files:I
.field public static final trae_chat_ref_searched_web:I
.field public static final trae_chat_ref_web_result:I
.field public static final trae_chat_searched_files:I
.field public static final trae_chat_status_command_running:I
.field public static final trae_chat_status_done:I
.field public static final trae_chat_status_failed:I
.field public static final trae_chat_status_generating_code:I
.field public static final trae_chat_status_pending:I
.field public static final trae_chat_status_thinking:I
.field public static final trae_chat_stream_canceled:I
.field public static final trae_chat_stream_canceled_title:I
.field public static final trae_chat_stream_error_title:I
.field public static final trae_chat_stream_tips_title:I
.field public static final trae_chat_stream_warning_title:I
.field public static final trae_chat_sub_agent_default:I
.field public static final trae_chat_summary_title:I
.field public static final trae_chat_thinking_collapsed:I
.field public static final trae_chat_thinking_expanded:I
.field public static final trae_chat_todo_completed:I
.field public static final trae_chat_todo_in_progress:I
.field public static final trae_chat_token_count:I
.field public static final trae_chat_tool_ask_answer_other:I
.field public static final trae_chat_tool_ask_custom_input:I
.field public static final trae_chat_tool_asked_user:I
.field public static final trae_chat_tool_asking_user:I
.field public static final trae_chat_tool_authorization_completed:I
.field public static final trae_chat_tool_authorization_failed:I
.field public static final trae_chat_tool_authorization_skipped:I
.field public static final trae_chat_tool_authorization_waiting:I
.field public static final trae_chat_tool_browser_failed:I
.field public static final trae_chat_tool_browser_used:I
.field public static final trae_chat_tool_browser_user_declined:I
.field public static final trae_chat_tool_browser_user_takeover:I
.field public static final trae_chat_tool_browser_user_taking_over:I
.field public static final trae_chat_tool_browser_using:I
.field public static final trae_chat_tool_browser_waiting_takeover:I
.field public static final trae_chat_tool_canceled:I
.field public static final trae_chat_tool_cmd_canceled:I
.field public static final trae_chat_tool_cmd_command:I
.field public static final trae_chat_tool_cmd_failed:I
.field public static final trae_chat_tool_cmd_no_output:I
.field public static final trae_chat_tool_cmd_output:I
.field public static final trae_chat_tool_cmd_ran:I
.field public static final trae_chat_tool_cmd_running:I
.field public static final trae_chat_tool_created:I
.field public static final trae_chat_tool_creating:I
.field public static final trae_chat_tool_delete:I
.field public static final trae_chat_tool_deleted:I
.field public static final trae_chat_tool_deleting:I
.field public static final trae_chat_tool_edited:I
.field public static final trae_chat_tool_editing:I
.field public static final trae_chat_tool_env_failed:I
.field public static final trae_chat_tool_env_set_up:I
.field public static final trae_chat_tool_env_setting_up:I
.field public static final trae_chat_tool_failed_create:I
.field public static final trae_chat_tool_failed_delete:I
.field public static final trae_chat_tool_failed_edit:I
.field public static final trae_chat_tool_failed_read:I
.field public static final trae_chat_tool_fallback_called:I
.field public static final trae_chat_tool_fallback_calling:I
.field public static final trae_chat_tool_fallback_failed:I
.field public static final trae_chat_tool_fallback_input:I
.field public static final trae_chat_tool_fallback_output:I
.field public static final trae_chat_tool_image_failed:I
.field public static final trae_chat_tool_image_generated:I
.field public static final trae_chat_tool_image_generating:I
.field public static final trae_chat_tool_image_policy_violated:I
.field public static final trae_chat_tool_launched_skill:I
.field public static final trae_chat_tool_launching_skill:I
.field public static final trae_chat_tool_mcp_called:I
.field public static final trae_chat_tool_mcp_calling:I
.field public static final trae_chat_tool_mcp_canceled:I
.field public static final trae_chat_tool_mcp_failed:I
.field public static final trae_chat_tool_mcp_response:I
.field public static final trae_chat_tool_mcp_running:I
.field public static final trae_chat_tool_mcp_waiting:I
.field public static final trae_chat_tool_no_matches:I
.field public static final trae_chat_tool_read_done:I
.field public static final trae_chat_tool_reading_files:I
.field public static final trae_chat_tool_search_failed:I
.field public static final trae_chat_tool_search_failed_codebase:I
.field public static final trae_chat_tool_search_failed_workspace:I
.field public static final trae_chat_tool_search_found_files:I
.field public static final trae_chat_tool_search_found_lines:I
.field public static final trae_chat_tool_search_found_occurrences:I
.field public static final trae_chat_tool_search_found_results:I
.field public static final trae_chat_tool_search_no_matches:I
.field public static final trae_chat_tool_search_no_results:I
.field public static final trae_chat_tool_searched_codebase:I
.field public static final trae_chat_tool_searched_workspace:I
.field public static final trae_chat_tool_searching:I
.field public static final trae_chat_tool_searching_codebase:I
.field public static final trae_chat_tool_searching_workspace:I
.field public static final trae_chat_tool_todo_all_completed:I
.field public static final trae_chat_tool_todo_updating:I
.field public static final trae_chat_tool_web_search_failed:I
.field public static final trae_chat_tool_web_search_no_matches:I
.field public static final trae_chat_tool_web_search_no_results:I
.field public static final trae_chat_tool_web_searched:I
.field public static final trae_chat_tool_web_searching:I
.field public static final trae_chat_toolcall_action_fallback:I
.field public static final trae_chat_toolcall_browser:I
.field public static final trae_chat_toolcall_file_fallback:I
.field public static final trae_chat_toolcall_task_list_updated:I
.field public static final trae_chat_user_message_show_more:I
.field public static final trae_chat_worked_minutes:I
.field public static final trae_chat_worked_seconds:I
.field public static final trae_chat_working:I
.field public static final trae_checkpoint_allow:I
.field public static final trae_checkpoint_ask_user_default_title:I
.field public static final trae_checkpoint_browser_action_title:I
.field public static final trae_checkpoint_browser_confirm:I
.field public static final trae_checkpoint_browser_fallback_desc:I
.field public static final trae_checkpoint_browser_hand_over:I
.field public static final trae_checkpoint_browser_header_label:I
.field public static final trae_checkpoint_browser_skip:I
.field public static final trae_checkpoint_browser_skip_hand_over:I
.field public static final trae_checkpoint_cancel:I
.field public static final trae_checkpoint_confirm:I
.field public static final trae_checkpoint_confirm_fallback_message:I
.field public static final trae_checkpoint_default_question:I
.field public static final trae_checkpoint_delete:I
.field public static final trae_checkpoint_delete_file_title:I
.field public static final trae_checkpoint_deny:I
.field public static final trae_checkpoint_dismissed_toast:I
.field public static final trae_checkpoint_execute:I
.field public static final trae_checkpoint_exit_plan_message:I
.field public static final trae_checkpoint_exit_plan_title:I
.field public static final trae_checkpoint_fallback_title:I
.field public static final trae_checkpoint_input_hint:I
.field public static final trae_checkpoint_mcp_call_title:I
.field public static final trae_checkpoint_mcp_unknown:I
.field public static final trae_checkpoint_next:I
.field public static final trae_checkpoint_notify_user_title:I
.field public static final trae_checkpoint_prev:I
.field public static final trae_checkpoint_progress:I
.field public static final trae_checkpoint_run:I
.field public static final trae_checkpoint_run_command_title:I
.field public static final trae_checkpoint_skip:I
.field public static final trae_checkpoint_submit:I
.field public static final trae_checkpoint_supplementary_hint:I
.field public static final trae_checkpoint_supplementary_question:I
.field public static final trae_checkpoint_timeout_description:I
.field public static final trae_checkpoint_timeout_title:I
.field public static final trae_checkpoint_view_detail:I
.field public static final trae_checkpoint_warning_blacklist:I
.field public static final trae_checkpoint_warning_command_label:I
.field public static final trae_checkpoint_warning_manual:I
.field public static final trae_checkpoint_warning_redlist:I
.field public static final trae_checkpoint_warning_sandbox_failure:I
.field public static final trae_checkpoint_warning_sandbox_not_block:I
.field public static final trae_checkpoint_warning_sandbox_recovery:I
.field public static final trae_checkpoint_warning_sandbox_unavailable:I
.field public static final trae_connect_guide_awaiting_authorization:I
.field public static final trae_connect_guide_connected:I
.field public static final trae_connect_guide_connected_to_pc:I
.field public static final trae_connect_guide_share:I
.field public static final trae_connect_guide_waiting_connection:I
.field public static final trae_credits_exhausted:I
.field public static final trae_credits_exhausted_title:I
.field public static final trae_credits_low_balance:I
.field public static final trae_device_activate_description:I
.field public static final trae_device_activate_ide_description:I
.field public static final trae_device_activate_title:I
.field public static final trae_device_activate_work_description:I
.field public static final trae_device_add_target_ide:I
.field public static final trae_device_add_target_work:I
.field public static final trae_device_connect_ide_step1:I
.field public static final trae_device_connect_ide_step2:I
.field public static final trae_device_connect_ide_step3:I
.field public static final trae_device_connect_ide_title:I
.field public static final trae_device_connect_work_step1:I
.field public static final trae_device_connect_work_step2:I
.field public static final trae_device_connect_work_step3:I
.field public static final trae_device_connect_work_title:I
.field public static final trae_device_management_add_device:I
.field public static final trae_device_management_add_device_subtitle:I
.field public static final trae_device_management_url_copied:I
.field public static final trae_device_status_offline:I
.field public static final trae_device_status_online:I
.field public static final trae_device_status_unpaired:I
.field public static final trae_device_target_select_ide_subtitle:I
.field public static final trae_device_target_select_work_subtitle:I
.field public static final trae_directory_empty:I
.field public static final trae_group_done_ask_user:I
.field public static final trae_group_done_browser_use:I
.field public static final trae_group_done_command_confirm:I
.field public static final trae_group_done_command_exec:I
.field public static final trae_group_done_env_init:I
.field public static final trae_group_done_file_create:I
.field public static final trae_group_done_file_delete:I
.field public static final trae_group_done_file_edit:I
.field public static final trae_group_done_file_search:I
.field public static final trae_group_done_file_view:I
.field public static final trae_group_done_folder_view:I
.field public static final trae_group_done_mcp_tool:I
.field public static final trae_group_done_preview:I
.field public static final trae_group_done_skill:I
.field public static final trae_group_done_task_manage:I
.field public static final trae_group_done_thinking:I
.field public static final trae_group_done_web_search:I
.field public static final trae_group_running_ask_user:I
.field public static final trae_group_running_browser_use:I
.field public static final trae_group_running_command_confirm:I
.field public static final trae_group_running_command_exec:I
.field public static final trae_group_running_env_init:I
.field public static final trae_group_running_file_create:I
.field public static final trae_group_running_file_delete:I
.field public static final trae_group_running_file_edit:I
.field public static final trae_group_running_file_search:I
.field public static final trae_group_running_file_view:I
.field public static final trae_group_running_folder_view:I
.field public static final trae_group_running_mcp_tool:I
.field public static final trae_group_running_preview:I
.field public static final trae_group_running_skill:I
.field public static final trae_group_running_task_manage:I
.field public static final trae_group_running_thinking:I
.field public static final trae_group_running_web_search:I
.field public static final trae_group_summary_command_exec:I
.field public static final trae_group_summary_file_create:I
.field public static final trae_group_summary_file_delete:I
.field public static final trae_group_summary_file_edit:I
.field public static final trae_group_summary_file_search:I
.field public static final trae_group_summary_file_view:I
.field public static final trae_group_summary_folder_view:I
.field public static final trae_group_summary_mcp_tool:I
.field public static final trae_group_summary_skill:I
.field public static final trae_group_summary_web_search:I
.field public static final trae_group_title_separator:I
.field public static final trae_html_artifact_copied:I
.field public static final trae_html_artifact_copy_link:I
.field public static final trae_html_artifact_download_zip:I
.field public static final trae_html_artifact_export_as_zip:I
.field public static final trae_html_artifact_generate_link:I
.field public static final trae_html_artifact_generating_link:I
.field public static final trae_html_artifact_link_copied:I
.field public static final trae_html_artifact_link_expires:I
.field public static final trae_html_artifact_link_generate_failed:I
.field public static final trae_html_artifact_loading_sandbox:I
.field public static final trae_html_artifact_reload:I
.field public static final trae_html_artifact_share_artifact:I
.field public static final trae_html_artifact_share_link_desc:I
.field public static final trae_html_artifact_share_link_desc_shared:I
.field public static final trae_html_artifact_share_link_title:I
.field public static final trae_html_artifact_stop_sharing:I
.field public static final trae_html_artifact_temporary_link:I
.field public static final trae_html_artifact_title_file_management:I
.field public static final trae_html_artifact_unable_to_open:I
.field public static final trae_ide_project_empty:I
.field public static final trae_ide_project_footer_hint:I
.field public static final trae_ide_project_name_unsaved_workspace:I
.field public static final trae_ide_project_name_workspace:I
.field public static final trae_ide_project_title:I
.field public static final trae_message_menu_copy:I
.field public static final trae_message_menu_delete:I
.field public static final trae_message_menu_report:I
.field public static final trae_message_menu_retry:I
.field public static final trae_message_menu_revert:I
.field public static final trae_message_menu_select_text:I
.field public static final trae_network_disconnected:I
.field public static final trae_new_feature_prompt_ide_connect:I
.field public static final trae_new_feature_prompt_ide_message:I
.field public static final trae_new_feature_prompt_ide_title:I
.field public static final trae_new_feature_prompt_later:I
.field public static final trae_new_feature_prompt_work_connect:I
.field public static final trae_new_feature_prompt_work_message:I
.field public static final trae_new_feature_prompt_work_title:I
.field public static final trae_plugin_authorization_authorize:I
.field public static final trae_plugin_authorization_authorized:I
.field public static final trae_plugin_authorization_body:I
.field public static final trae_plugin_authorization_cancel:I
.field public static final trae_plugin_authorization_desktop_footer:I
.field public static final trae_plugin_authorization_desktop_message:I
.field public static final trae_plugin_authorization_desktop_status:I
.field public static final trae_plugin_authorization_desktop_subtitle:I
.field public static final trae_plugin_authorization_desktop_title:I
.field public static final trae_plugin_authorization_qrcode_desc:I
.field public static final trae_plugin_authorization_qrcode_status:I
.field public static final trae_plugin_authorization_title:I
.field public static final trae_plugin_authorization_waiting:I
.field public static final trae_plugin_provider_name_dingtalk:I
.field public static final trae_plugin_provider_name_tencent_docs:I
.field public static final trae_plugin_provider_name_wecom:I
.field public static final trae_report_cancel:I
.field public static final trae_report_confirm:I
.field public static final trae_report_confirm_message:I
.field public static final trae_report_confirm_title:I
.field public static final trae_report_submit_failed:I
.field public static final trae_report_submit_success:I
.field public static final trae_select_project_permission_allow:I
.field public static final trae_select_project_permission_cancel:I
.field public static final trae_select_project_permission_subtitle:I
.field public static final trae_select_project_permission_title:I
.field public static final trae_skills_empty:I
.field public static final trae_skills_empty_ide:I
.field public static final trae_skills_error_lite_offline_content:I
.field public static final trae_skills_error_offline_content:I
.field public static final trae_skills_error_offline_title:I
.field public static final trae_skills_error_project_offline_content:I
.field public static final trae_thinking_title_complete:I
.field public static final trae_thinking_title_running:I
.field public static final trae_upgrade_reminder_body:I
.field public static final trae_upgrade_reminder_button:I
.field public static final trae_upgrade_reminder_title:I
.field public static final trae_voice_discussing:I


.method private constructor <init>()void
    .registers 1
    # ins_size=1
    invoke-direct v0, Ljava/lang/Object;-><init>()V
    return-void 
.end method
