package com.lynx.canvas;

/* loaded from: classes6.dex */
public class LynxKryptonTraceEventDef {
    public static final String LYNX_KRYPTON_HANDLE_STREAM_WITH_DELEGATE = "LYNX_KRYPTON_HANDLE_STREAM_WITH_DELEGATE";
    public static final String LYNX_KRYPTON_HANDLE_STREAM_WITH_RESOLVER = "LYNX_KRYPTON_HANDLE_STREAM_WITH_RESOLVER";
    public static final String LYNX_KRYPTON_LOADER_REDIRECT_URL = "LYNX_KRYPTON_LOADER_REDIRECT_URL";
    public static final String LYNX_KRYPTON_LOAD_DATA_URI = "LYNX_KRYPTON_LOAD_DATA_URI";
    public static final String LYNX_KRYPTON_LOAD_LOCAL_PATH_RESOURCE = "LYNX_KRYPTON_LOAD_LOCAL_PATH_RESOURCE";
    public static final String LYNX_KRYPTON_LOAD_WITH_GENERIC_FETCHER = "LYNX_KRYPTON_LOAD_WITH_GENERIC_FETCHER";
    public static final String LYNX_KRYPTON_LOAD_WITH_IMAGE_SERVICE = "LYNX_KRYPTON_LOAD_WITH_IMAGE_SERVICE";
    public static final String LYNX_KRYPTON_LOAD_WITH_RESOURCE_SERVICE = "LYNX_KRYPTON_LOAD_WITH_RESOURCE_SERVICE";
    public static final String LYNX_KRYPTON_LOAD_WITH_RES_MANAGER = "LYNX_KRYPTON_LOAD_WITH_RES_MANAGER";
}
