package com.bytedance.lynx.service.image;

import com.bytedance.lynx.service.image.utils.ImageUtils;
import com.facebook.cache.disk.DiskStorageCache;
import com.facebook.cache.disk.DynamicDefaultDiskStorage;
import com.facebook.common.executors.ConstrainedExecutorService;
import com.facebook.common.internal.Suppliers;
import com.facebook.common.statfs.StatFsHelper;
import com.facebook.common.util.HashCodeUtil;
import com.facebook.common.util.UriUtil;
import com.facebook.datasource.BaseDataSubscriber;
import com.facebook.drawee.backends.pipeline.DefaultDrawableFactory;
import com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilder;
import com.facebook.drawee.controller.BaseControllerListener;
import com.facebook.drawee.drawable.ArrayDrawable;
import com.facebook.drawee.drawable.DrawableProperties;
import com.facebook.drawee.drawable.DrawableUtils;
import com.facebook.drawee.drawable.FadeDrawable;
import com.facebook.drawee.drawable.ForwardingDrawable;
import com.facebook.drawee.drawable.RoundedColorDrawable;
import com.facebook.drawee.drawable.ScaleTypeDrawable;
import com.facebook.drawee.generic.GenericDraweeHierarchy;
import com.facebook.drawee.generic.GenericDraweeHierarchyBuilder;
import com.facebook.drawee.generic.RoundingParams;
import com.facebook.drawee.generic.WrappingUtils;
import com.facebook.fresco.animation.factory.AnimatedFactoryV2Impl;
import com.facebook.fresco.animation.factory.ExperimentalBitmapAnimationDrawableFactory;
import com.facebook.imageformat.DefaultImageFormatChecker;
import com.facebook.imageformat.ImageFormatChecker;
import com.facebook.imagepipeline.bitmaps.ArtBitmapFactory;
import com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory;
import com.facebook.imagepipeline.cache.BitmapCountingMemoryCacheFactory;
import com.facebook.imagepipeline.cache.BitmapMemoryCacheFactory;
import com.facebook.imagepipeline.cache.BitmapMemoryCacheKey;
import com.facebook.imagepipeline.cache.BufferedDiskCache;
import com.facebook.imagepipeline.cache.CountingLruMap;
import com.facebook.imagepipeline.cache.CountingMemoryCache;
import com.facebook.imagepipeline.cache.HashMapMemoryCache;
import com.facebook.imagepipeline.cache.StagingArea;
import com.facebook.imagepipeline.common.ImageDecodeOptions;
import com.facebook.imagepipeline.common.ImageDecodeOptionsBuilder;
import com.facebook.imagepipeline.common.Priority;
import com.facebook.imagepipeline.common.ResizeOptions;
import com.facebook.imagepipeline.common.RotationOptions;
import com.facebook.imagepipeline.core.ImagePipeline;
import com.facebook.imagepipeline.core.ProducerFactory;
import com.facebook.imagepipeline.core.ProducerSequenceFactory;
import com.facebook.imagepipeline.decoder.DefaultImageDecoder;
import com.facebook.imagepipeline.listener.ForwardingRequestListener;
import com.facebook.imagepipeline.memory.BucketsBitmapPool;
import com.facebook.imagepipeline.platform.DefaultDecoder;
import com.facebook.imagepipeline.platform.OreoDecoder;
import com.facebook.imagepipeline.producers.NetworkFetchProducer;
import com.facebook.imagepipeline.request.ImageRequest;
import com.facebook.imagepipeline.request.ImageRequestBuilder;
import com.facebook.imagepipeline.transcoder.MultiImageTranscoderFactory;
import com.lynx.tasm.BehaviorClassWarmer;
import com.lynx.tasm.behavior.ui.image.FlattenUIImage;
import com.lynx.tasm.behavior.ui.image.LynxImageManager;
import com.lynx.tasm.behavior.ui.image.UIImage;
import com.lynx.tasm.image.AutoSizeImage;
import com.lynx.tasm.image.LynxScaleTypeDrawable;
import com.lynx.tasm.image.ScalingUtils;
import com.lynx.tasm.image.model.ImageRequestInfo;
import com.lynx.tasm.image.model.ImageRequestInfoBuilder;

/* loaded from: /data/user/work/trae_cn3_decoded/build/apk/classes4.dex */
public class UIImageClassWarmer implements BehaviorClassWarmer {
    public void warmClass() {
        try {
            Class.forName(FlattenUIImage.class.getName());
            Class.forName(LynxScaleTypeDrawable.class.getName());
            Class.forName(ScalingUtils.class.getName());
            Class.forName(ScalingUtils.ScaleType.class.getName());
            Class.forName(LynxImageManager.class.getName());
            Class.forName(UIImage.class.getName());
            Class.forName(ImageUtils.class.getName());
            Class.forName(AutoSizeImage.class.getName());
            Class.forName(ImageRequestInfoBuilder.class.getName());
            Class.forName(ImageRequestInfo.class.getName());
            Class.forName(LynxImageService.class.getName());
            Class.forName(DefaultDrawableFactory.class.getName());
            Class.forName(DefaultDecoder.class.getName());
            Class.forName(PlatformBitmapFactory.class.getName());
            Class.forName(CountingMemoryCache.class.getName());
            Class.forName(CountingLruMap.class.getName());
            Class.forName(DiskStorageCache.class.getName());
            Class.forName(ProducerSequenceFactory.class.getName());
            Class.forName(ImagePipeline.class.getName());
            Class.forName(ExperimentalBitmapAnimationDrawableFactory.class.getName());
            Class.forName(DefaultImageDecoder.class.getName());
            Class.forName(BufferedDiskCache.class.getName());
            Class.forName(ProducerFactory.class.getName());
            Class.forName(NetworkFetchProducer.class.getName());
            Class.forName(AnimatedFactoryV2Impl.class.getName());
            Class.forName(PipelineDraweeControllerBuilder.class.getName());
            Class.forName(BaseControllerListener.class.getName());
            Class.forName(GenericDraweeHierarchyBuilder.class.getName());
            Class.forName(RoundingParams.class.getName());
            Class.forName(GenericDraweeHierarchy.class.getName());
            Class.forName(ForwardingDrawable.class.getName());
            Class.forName(DrawableProperties.class.getName());
            Class.forName(DrawableUtils.class.getName());
            Class.forName(WrappingUtils.class.getName());
            Class.forName(ScaleTypeDrawable.class.getName());
            Class.forName(ArrayDrawable.class.getName());
            Class.forName(FadeDrawable.class.getName());
            Class.forName(RoundedColorDrawable.class.getName());
            Class.forName(ImageRequestBuilder.class.getName());
            Class.forName(ImageDecodeOptionsBuilder.class.getName());
            Class.forName(ImageDecodeOptions.class.getName());
            Class.forName(ImageRequest.class.getName());
            Class.forName(ImageRequest.RequestLevel.class.getName());
            Class.forName(ImageRequest.CacheChoice.class.getName());
            Class.forName(Priority.class.getName());
            Class.forName(RotationOptions.class.getName());
            Class.forName(ResizeOptions.class.getName());
            Class.forName(UriUtil.class.getName());
            Class.forName(BitmapMemoryCacheKey.class.getName());
            Class.forName(HashCodeUtil.class.getName());
            Class.forName(BucketsBitmapPool.class.getName());
            Class.forName(BitmapCountingMemoryCacheFactory.class.getName());
            Class.forName(HashMapMemoryCache.class.getName());
            Class.forName(ConstrainedExecutorService.class.getName());
            Class.forName(ImageFormatChecker.class.getName());
            Class.forName(DynamicDefaultDiskStorage.class.getName());
            Class.forName(StatFsHelper.class.getName());
            Class.forName(ForwardingRequestListener.class.getName());
            Class.forName(StagingArea.class.getName());
            Class.forName(MultiImageTranscoderFactory.class.getName());
            Class.forName(Suppliers.class.getName());
            Class.forName(DefaultImageFormatChecker.class.getName());
            Class.forName(BitmapMemoryCacheFactory.class.getName());
            Class.forName(ArtBitmapFactory.class.getName());
            Class.forName(OreoDecoder.class.getName());
            Class.forName(BaseDataSubscriber.class.getName());
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }
}
