# Decompiled TRAE business class
# Source DEX: classes5.dex
.class public final Lcom/bytedance/trae/home/R$dimen;
.super Ljava/lang/Object;

.field public static final trae_dp_30:I
.field public static final trae_dp_5:I
.field public static final trae_dp_72:I
.field public static final trae_dp_75:I
.field public static final trae_setting_about_icon_margin_start:I
.field public static final trae_setting_about_icon_padding:I
.field public static final trae_setting_about_icon_size:I
.field public static final trae_setting_about_text_margin_start:I
.field public static final trae_setting_account_phone_icon_size:I
.field public static final trae_setting_add_device_button_height:I
.field public static final trae_setting_add_device_button_radius:I
.field public static final trae_setting_avatar_container:I
.field public static final trae_setting_avatar_edit_margin:I
.field public static final trae_setting_avatar_margin_top:I
.field public static final trae_setting_avatar_preview:I
.field public static final trae_setting_avatar_size:I
.field public static final trae_setting_back_btn_size:I
.field public static final trae_setting_back_margin_start:I
.field public static final trae_setting_back_padding:I
.field public static final trae_setting_badge_padding_h:I
.field public static final trae_setting_camera_icon_size:I
.field public static final trae_setting_camera_margin:I
.field public static final trae_setting_camera_padding:I
.field public static final trae_setting_card_radius:I
.field public static final trae_setting_chevron_margin_end:I
.field public static final trae_setting_chevron_size:I
.field public static final trae_setting_close_btn_size:I
.field public static final trae_setting_close_btn_size_new:I
.field public static final trae_setting_close_icon_size:I
.field public static final trae_setting_close_icon_size_new:I
.field public static final trae_setting_close_margin_end:I
.field public static final trae_setting_corner_radius:I
.field public static final trae_setting_device_empty_hero_height:I
.field public static final trae_setting_device_empty_hero_margin_top:I
.field public static final trae_setting_device_empty_hero_radius:I
.field public static final trae_setting_device_empty_steps_gap:I
.field public static final trae_setting_device_empty_steps_width:I
.field public static final trae_setting_device_empty_tab_indicator_height:I
.field public static final trae_setting_device_empty_tab_indicator_width:I
.field public static final trae_setting_device_empty_tabs_height:I
.field public static final trae_setting_device_icon_container_radius:I
.field public static final trae_setting_device_icon_container_size:I
.field public static final trae_setting_device_icon_size:I
.field public static final trae_setting_device_item_height:I
.field public static final trae_setting_device_item_padding_vertical:I
.field public static final trae_setting_device_status_height:I
.field public static final trae_setting_device_status_min_width:I
.field public static final trae_setting_device_status_padding_h:I
.field public static final trae_setting_device_status_radius:I
.field public static final trae_setting_dialog_btn_gap:I
.field public static final trae_setting_dialog_btn_height:I
.field public static final trae_setting_dialog_btn_margin_top:I
.field public static final trae_setting_dialog_input_height:I
.field public static final trae_setting_dialog_input_margin_top:I
.field public static final trae_setting_dialog_input_padding_h:I
.field public static final trae_setting_dialog_padding_bottom:I
.field public static final trae_setting_dialog_padding_h:I
.field public static final trae_setting_dialog_padding_top:I
.field public static final trae_setting_divider_height:I
.field public static final trae_setting_drag_handle_height:I
.field public static final trae_setting_drag_handle_margin_bottom:I
.field public static final trae_setting_drag_handle_margin_top:I
.field public static final trae_setting_drag_handle_width:I
.field public static final trae_setting_edit_btn_margin_top:I
.field public static final trae_setting_edit_btn_padding_h:I
.field public static final trae_setting_edit_btn_padding_v:I
.field public static final trae_setting_email_margin_top:I
.field public static final trae_setting_group_padding_vertical:I
.field public static final trae_setting_icon_inner_padding:I
.field public static final trae_setting_icon_margin_start:I
.field public static final trae_setting_icon_size:I
.field public static final trae_setting_identity_tag_height:I
.field public static final trae_setting_identity_tag_padding_horizontal:I
.field public static final trae_setting_item_min_height:I
.field public static final trae_setting_item_padding_vertical:I
.field public static final trae_setting_item_padding_vertical_lg:I
.field public static final trae_setting_margin_bottom_last:I
.field public static final trae_setting_margin_group:I
.field public static final trae_setting_margin_sub_group:I
.field public static final trae_setting_name_margin_start:I
.field public static final trae_setting_padding_horizontal:I
.field public static final trae_setting_points_value_padding_horizontal:I
.field public static final trae_setting_popup_item_padding_h:I
.field public static final trae_setting_popup_item_padding_v:I
.field public static final trae_setting_popup_width:I
.field public static final trae_setting_privacy_details_margin_top:I
.field public static final trae_setting_product_tag_height:I
.field public static final trae_setting_product_tag_line_height:I
.field public static final trae_setting_product_tag_margin_top:I
.field public static final trae_setting_product_tag_padding_h:I
.field public static final trae_setting_product_tag_padding_v:I
.field public static final trae_setting_product_tag_radius:I
.field public static final trae_setting_profile_padding_bottom:I
.field public static final trae_setting_profile_padding_h:I
.field public static final trae_setting_save_padding:I
.field public static final trae_setting_selector_margin_start:I
.field public static final trae_setting_single_item_padding_vertical:I
.field public static final trae_setting_size_zero:I
.field public static final trae_setting_sub_toolbar_height:I
.field public static final trae_setting_swipe_action_icon_container_size:I
.field public static final trae_setting_swipe_action_width:I
.field public static final trae_setting_swipe_delete_icon_size:I
.field public static final trae_setting_swipe_label_margin_top:I
.field public static final trae_setting_swipe_rename_icon_size:I
.field public static final trae_setting_text_badge:I
.field public static final trae_setting_text_body:I
.field public static final trae_setting_text_caption:I
.field public static final trae_setting_text_item:I
.field public static final trae_setting_text_name:I
.field public static final trae_setting_text_secondary:I
.field public static final trae_setting_text_title:I
.field public static final trae_setting_text_upgrade:I
.field public static final trae_setting_toolbar_height:I
.field public static final trae_setting_upgrade_padding:I
.field public static final trae_solo_filter_device_content_height:I
.field public static final trae_solo_filter_device_horizontal_padding:I
.field public static final trae_solo_filter_device_icon_size:I
.field public static final trae_solo_filter_device_icon_text_gap:I
.field public static final trae_solo_filter_device_item_height:I
.field public static final trae_solo_filter_product_tag_height:I
.field public static final trae_solo_filter_product_tag_line_height:I
.field public static final trae_solo_filter_product_tag_margin_top:I
.field public static final trae_solo_filter_product_tag_padding_horizontal:I
.field public static final trae_solo_task_content_margin_top:I
.field public static final trae_solo_task_search_empty_gap:I
.field public static final trae_solo_task_search_empty_icon_size:I
.field public static final trae_solo_task_search_input_radius:I
.field public static final trae_solo_task_title_bar_margin_top:I
.field public static final trae_sp_10:I
.field public static final trae_task_icon_circle_border_width:I
.field public static final trae_task_icon_circle_dash_gap:I
.field public static final trae_task_icon_circle_dash_width:I
.field public static final trae_task_item_divider_height:I
.field public static final trae_task_item_divider_horizontal_margin:I
.field public static final trae_task_swipe_action_gap:I
.field public static final trae_task_swipe_action_icon_size:I
.field public static final trae_task_swipe_action_label_margin_top:I
.field public static final trae_task_swipe_action_label_text_size:I
.field public static final trae_task_swipe_action_size:I


.method private constructor <init>()void
    .registers 1
    # ins_size=1
    invoke-direct v0, Ljava/lang/Object;-><init>()V
    return-void 
.end method
