# Decompiled TRAE business class
# Source DEX: classes5.dex
.class public final Lcom/bytedance/trae/home/R$drawable;
.super Ljava/lang/Object;

.field public static final bg_about_logo_rounded:I
.field public static final bg_account_settings_sheet:I
.field public static final bg_btn_binding_primary:I
.field public static final bg_btn_binding_secondary:I
.field public static final bg_btn_dialog_primary:I
.field public static final bg_circle_close:I
.field public static final bg_circle_white:I
.field public static final bg_close_btn:I
.field public static final bg_cn_pro_badge:I
.field public static final bg_cn_tier_badge:I
.field public static final bg_danger_btn:I
.field public static final bg_dialog_btn:I
.field public static final bg_dialog_input:I
.field public static final bg_dialog_rounded:I
.field public static final bg_drag_handle:I
.field public static final bg_edit_profile_btn:I
.field public static final bg_empty_icon_container:I
.field public static final bg_message_badge:I
.field public static final bg_popup_language:I
.field public static final bg_popup_menu:I
.field public static final bg_privacy_btn_primary:I
.field public static final bg_privacy_btn_secondary:I
.field public static final bg_pro_badge:I
.field public static final bg_setting_add_device_btn:I
.field public static final bg_setting_device_empty_hero:I
.field public static final bg_setting_device_icon_container:I
.field public static final bg_setting_device_item:I
.field public static final bg_setting_device_status_offline:I
.field public static final bg_setting_device_status_online:I
.field public static final bg_setting_device_status_unpaired:I
.field public static final bg_setting_group:I
.field public static final bg_setting_icon_rounded:I
.field public static final bg_settings_section:I
.field public static final bg_site_message_card:I
.field public static final bg_site_message_cta:I
.field public static final bg_site_message_settings_card:I
.field public static final bg_site_message_unread_dot:I
.field public static final bg_skills_bottom_sheet:I
.field public static final bg_skills_close_btn:I
.field public static final bg_skills_indicator:I
.field public static final bg_solo_avatar_placeholder:I
.field public static final bg_solo_badge_dot:I
.field public static final bg_solo_bottom_sheet:I
.field public static final bg_solo_chat_nav:I
.field public static final bg_solo_dialog:I
.field public static final bg_solo_dialog_btn_danger:I
.field public static final bg_solo_dialog_btn_default:I
.field public static final bg_solo_dialog_input:I
.field public static final bg_solo_filter_popup:I
.field public static final bg_solo_notification_dot:I
.field public static final bg_solo_swipe_delete:I
.field public static final bg_solo_swipe_pin:I
.field public static final bg_solo_swipe_rename:I
.field public static final bg_solo_task_icon_circle:I
.field public static final bg_solo_task_initial:I
.field public static final bg_solo_task_status:I
.field public static final bg_solo_task_tag:I
.field public static final bg_splash_window:I
.field public static final bg_task_search_exit:I
.field public static final bg_task_search_input:I
.field public static final bg_toggle_thumb:I
.field public static final bg_toggle_track:I
.field public static final bg_upgrade_btn:I
.field public static final chat_new_dashed:I
.field public static final chevron_up:I
.field public static final cloud:I
.field public static final cmp_device_guide_ide_hero:I
.field public static final cmp_device_guide_work_hero:I
.field public static final cmp_ic_device_action_delete:I
.field public static final cmp_ic_device_action_rename:I
.field public static final cmp_ic_device_add:I
.field public static final cmp_ic_device_copy:I
.field public static final cmp_ic_device_menu_rename:I
.field public static final cmp_ic_device_pc:I
.field public static final cmp_ic_device_pc_offline:I
.field public static final cmp_ic_setting_chevron_right:I
.field public static final cmp_ic_setting_computer_screen:I
.field public static final cmp_ic_setting_connector_added:I
.field public static final cmp_ic_setting_debug:I
.field public static final cmp_ic_setting_info_circle:I
.field public static final cmp_ic_setting_language:I
.field public static final cmp_ic_setting_logout:I
.field public static final cmp_ic_setting_message:I
.field public static final cmp_ic_setting_notification:I
.field public static final cmp_ic_setting_points:I
.field public static final cmp_ic_setting_privacy:I
.field public static final cmp_ic_setting_selector_arrows:I
.field public static final cmp_ic_setting_subscription:I
.field public static final cmp_ic_setting_sun_day:I
.field public static final cmp_ic_setting_tokens:I
.field public static final cmp_ic_setting_trae:I
.field public static final cmp_ic_setting_trae_color:I
.field public static final cmp_ic_setting_user:I
.field public static final cmp_trae_default_avatar:I
.field public static final cmp_trae_ic_bytecloud_badge:I
.field public static final face_error:I
.field public static final folder:I
.field public static final ic_about_trae:I
.field public static final ic_account_douyin:I
.field public static final ic_account_phone:I
.field public static final ic_account_shield:I
.field public static final ic_account_trash:I
.field public static final ic_all:I
.field public static final ic_brainstorm:I
.field public static final ic_business_license:I
.field public static final ic_chevron_right:I
.field public static final ic_close_setting:I
.field public static final ic_close_skill:I
.field public static final ic_cloud:I
.field public static final ic_cloud_menu:I
.field public static final ic_connector:I
.field public static final ic_connector_github:I
.field public static final ic_connector_open_new_link:I
.field public static final ic_empty_message:I
.field public static final ic_empty_task:I
.field public static final ic_identity_l4:I
.field public static final ic_identity_pay:I
.field public static final ic_language:I
.field public static final ic_notification:I
.field public static final ic_privacy_ai_data:I
.field public static final ic_privacy_bluetooth:I
.field public static final ic_privacy_camera:I
.field public static final ic_privacy_clipboard:I
.field public static final ic_privacy_file_access:I
.field public static final ic_privacy_location:I
.field public static final ic_privacy_microphone:I
.field public static final ic_privacy_more:I
.field public static final ic_privacy_personalized:I
.field public static final ic_privacy_photo:I
.field public static final ic_privacy_push:I
.field public static final ic_privacy_shield:I
.field public static final ic_setting_back:I
.field public static final ic_setting_camera:I
.field public static final ic_setting_check:I
.field public static final ic_setting_chevron_right:I
.field public static final ic_setting_close:I
.field public static final ic_setting_close_small:I
.field public static final ic_setting_computer_screen:I
.field public static final ic_setting_computer_screen_offline:I
.field public static final ic_setting_connector_added:I
.field public static final ic_setting_debug:I
.field public static final ic_setting_external_link:I
.field public static final ic_setting_info_circle:I
.field public static final ic_setting_language:I
.field public static final ic_setting_logout:I
.field public static final ic_setting_message:I
.field public static final ic_setting_notification:I
.field public static final ic_setting_points:I
.field public static final ic_setting_privacy:I
.field public static final ic_setting_selector_arrows:I
.field public static final ic_setting_subscription:I
.field public static final ic_setting_sun_day:I
.field public static final ic_setting_tokens:I
.field public static final ic_setting_trae:I
.field public static final ic_setting_trae_color:I
.field public static final ic_setting_user:I
.field public static final ic_solo_bullet_task:I
.field public static final ic_solo_chat_new:I
.field public static final ic_solo_chat_new_filled:I
.field public static final ic_solo_checkmark_circle:I
.field public static final ic_solo_chevron_up:I
.field public static final ic_solo_cloud:I
.field public static final ic_solo_cloud_1:I
.field public static final ic_solo_cloud_small:I
.field public static final ic_solo_computer:I
.field public static final ic_solo_computer_offline:I
.field public static final ic_solo_computer_screen:I
.field public static final ic_solo_creating_circle:I
.field public static final ic_solo_delete:I
.field public static final ic_solo_delete_1:I
.field public static final ic_solo_drop_down:I
.field public static final ic_solo_dropdown:I
.field public static final ic_solo_edit:I
.field public static final ic_solo_edit_1:I
.field public static final ic_solo_edit_2:I
.field public static final ic_solo_failed_circle:I
.field public static final ic_solo_filter_all:I
.field public static final ic_solo_filter_checkmark:I
.field public static final ic_solo_filter_cloud:I
.field public static final ic_solo_filter_computer:I
.field public static final ic_solo_filter_computer_off:I
.field public static final ic_solo_filter_trae_ide:I
.field public static final ic_solo_filter_trae_work:I
.field public static final ic_solo_frozen_circle:I
.field public static final ic_solo_pin:I
.field public static final ic_solo_pin_1:I
.field public static final ic_solo_reverting_circle:I
.field public static final ic_solo_stopped_circle:I
.field public static final ic_solo_task_app:I
.field public static final ic_solo_task_business:I
.field public static final ic_solo_task_chat:I
.field public static final ic_solo_task_code:I
.field public static final ic_solo_task_code_type:I
.field public static final ic_solo_task_data:I
.field public static final ic_solo_task_design:I
.field public static final ic_solo_task_document:I
.field public static final ic_solo_task_folder:I
.field public static final ic_solo_task_image:I
.field public static final ic_solo_task_mine:I
.field public static final ic_solo_task_mine_1:I
.field public static final ic_solo_task_personal:I
.field public static final ic_solo_task_ppt:I
.field public static final ic_solo_task_research:I
.field public static final ic_solo_task_safari:I
.field public static final ic_solo_task_web:I
.field public static final ic_solo_todo:I
.field public static final ic_solo_trash:I
.field public static final ic_solo_unknown_circle:I
.field public static final ic_solo_unpin:I
.field public static final ic_solo_user:I
.field public static final ic_solo_warning_circle:I
.field public static final ic_tab_chat:I
.field public static final ic_tab_task:I
.field public static final ic_tab_user:I
.field public static final ic_task_product_ide:I
.field public static final ic_task_product_lite:I
.field public static final ic_task_product_local:I
.field public static final ic_task_search:I
.field public static final ic_task_search_clear:I
.field public static final ic_task_search_close:I
.field public static final ic_task_search_empty:I
.field public static final ic_theme:I
.field public static final ic_trash_red:I
.field public static final ic_trash_white:I
.field public static final logo_trae:I
.field public static final new_chat:I
.field public static final onboarding_btn_dark:I
.field public static final onboarding_btn_light:I
.field public static final onboarding_indicator_active:I
.field public static final onboarding_indicator_inactive:I
.field public static final onboarding_page_1:I
.field public static final onboarding_page_2:I
.field public static final onboarding_page_3:I
.field public static final solo_loading_ring:I
.field public static final splash_slogan:I
.field public static final splash_window_background:I
.field public static final trae_bg_edit_avatar_cancel_btn:I
.field public static final trae_bg_edit_avatar_ok_btn:I
.field public static final trae_bg_retry_button:I
.field public static final trae_default_avatar:I
.field public static final trae_ic_bytecloud_badge:I
.field public static final trae_ic_bytecloud_badge_small:I
.field public static final trae_ic_douyin:I
.field public static final trae_img_device_manager_tips:I
.field public static final trae_tab_icon_plus:I


.method private constructor <init>()void
    .registers 1
    # ins_size=1
    invoke-direct v0, Ljava/lang/Object;-><init>()V
    return-void 
.end method
