# Decompiled TRAE business class
# Source DEX: classes5.dex
.class public final Lcom/bytedance/trae/home/R$id;
.super Ljava/lang/Object;

.field public static final bottom_buttons_container:I
.field public static final btn_about:I
.field public static final btn_account:I
.field public static final btn_add_device:I
.field public static final btn_agree:I
.field public static final btn_back:I
.field public static final btn_business_license:I
.field public static final btn_camera_photo:I
.field public static final btn_cancel:I
.field public static final btn_cancel_confirm:I
.field public static final btn_cancel_oauth:I
.field public static final btn_cancel_pwd:I
.field public static final btn_cancel_sms:I
.field public static final btn_cancel_verify:I
.field public static final btn_clear:I
.field public static final btn_clear_billing_upgrade_prompt_cache:I
.field public static final btn_close:I
.field public static final btn_community:I
.field public static final btn_confirm:I
.field public static final btn_confirm_delete:I
.field public static final btn_connectors:I
.field public static final btn_contact:I
.field public static final btn_copy_device_info:I
.field public static final btn_copy_url:I
.field public static final btn_cta:I
.field public static final btn_custom_header_add:I
.field public static final btn_custom_header_clear_all:I
.field public static final btn_debug:I
.field public static final btn_delete:I
.field public static final btn_delete_account:I
.field public static final btn_device_management:I
.field public static final btn_disagree:I
.field public static final btn_douyin_action:I
.field public static final btn_edit_avatar:I
.field public static final btn_edit_name:I
.field public static final btn_edit_profile:I
.field public static final btn_env_lane_reset:I
.field public static final btn_env_lane_save:I
.field public static final btn_file_access:I
.field public static final btn_google_verify:I
.field public static final btn_help:I
.field public static final btn_icp_filing:I
.field public static final btn_language:I
.field public static final btn_logout:I
.field public static final btn_messages:I
.field public static final btn_notification:I
.field public static final btn_ok:I
.field public static final btn_ok_countdown:I
.field public static final btn_opensource:I
.field public static final btn_permission_usage:I
.field public static final btn_personal_info_list:I
.field public static final btn_phone_action:I
.field public static final btn_photo:I
.field public static final btn_pin:I
.field public static final btn_privacy:I
.field public static final btn_privacy_permission:I
.field public static final btn_push:I
.field public static final btn_pwd_verify:I
.field public static final btn_recording:I
.field public static final btn_rename:I
.field public static final btn_retry_network:I
.field public static final btn_save:I
.field public static final btn_send_code:I
.field public static final btn_share_list:I
.field public static final btn_sms_send_code:I
.field public static final btn_sms_verify:I
.field public static final btn_subscribe:I
.field public static final btn_task_search_clear:I
.field public static final btn_task_search_entry:I
.field public static final btn_task_search_exit:I
.field public static final btn_terms:I
.field public static final btn_theme:I
.field public static final btn_update:I
.field public static final btn_upload_alog:I
.field public static final btn_usage:I
.field public static final btn_verify:I
.field public static final btn_view_login_devices:I
.field public static final card_delete_account:I
.field public static final card_github:I
.field public static final card_login_methods:I
.field public static final card_manage_github:I
.field public static final cb_mock_did:I
.field public static final cmp_settings_entry_root:I
.field public static final dim_overlay:I
.field public static final divider_community:I
.field public static final divider_connectors:I
.field public static final divider_email:I
.field public static final divider_github:I
.field public static final divider_icp:I
.field public static final divider_license:I
.field public static final divider_permission:I
.field public static final divider_personal_info:I
.field public static final divider_phone:I
.field public static final divider_share_list:I
.field public static final divider_theme:I
.field public static final divider_update_about:I
.field public static final empty_guide_content:I
.field public static final empty_state:I
.field public static final et_custom_header_key:I
.field public static final et_custom_header_value:I
.field public static final et_email:I
.field public static final et_env_lane:I
.field public static final et_name:I
.field public static final et_password:I
.field public static final et_ppe_env:I
.field public static final et_sms_code:I
.field public static final et_task_search:I
.field public static final et_verification_code:I
.field public static final fab_add:I
.field public static final fl_avatar_container:I
.field public static final fl_icon_container:I
.field public static final floating_card:I
.field public static final fragment_container:I
.field public static final group_account_messages:I
.field public static final img_avatar_edit_indicator:I
.field public static final img_cn_identity:I
.field public static final indicator:I
.field public static final indicator_empty_guide_ide:I
.field public static final indicator_empty_guide_work:I
.field public static final item_all:I
.field public static final item_cloud:I
.field public static final item_device:I
.field public static final iv_avatar:I
.field public static final iv_avatar_preview:I
.field public static final iv_bytecloud_badge:I
.field public static final iv_check_all:I
.field public static final iv_check_cloud:I
.field public static final iv_check_device:I
.field public static final iv_chevron:I
.field public static final iv_device_icon:I
.field public static final iv_emoji_icon:I
.field public static final iv_icon:I
.field public static final iv_license:I
.field public static final iv_operation_icon:I
.field public static final iv_pin:I
.field public static final iv_product_icon:I
.field public static final iv_shield:I
.field public static final iv_source_icon:I
.field public static final iv_task_search_input_icon:I
.field public static final iv_task_search_loading:I
.field public static final layout_content:I
.field public static final layout_device_icon_container:I
.field public static final layout_empty_guide:I
.field public static final layout_empty_guide_tabs:I
.field public static final layout_empty_state:I
.field public static final layout_network_error:I
.field public static final layout_swipe_actions:I
.field public static final layout_task_search_empty_state:I
.field public static final layout_task_search_header:I
.field public static final layout_task_search_input:I
.field public static final layout_task_search_loading:I
.field public static final ll_custom_headers:I
.field public static final ll_delete:I
.field public static final ll_device_container:I
.field public static final ll_info_left:I
.field public static final ll_ppe_history:I
.field public static final ll_product_tag:I
.field public static final ll_product_type:I
.field public static final ll_rename:I
.field public static final ll_title_filter:I
.field public static final loading:I
.field public static final logo_image:I
.field public static final menu_delete:I
.field public static final menu_pin:I
.field public static final menu_rename:I
.field public static final pb_loading:I
.field public static final progress_loading:I
.field public static final root_container:I
.field public static final row_douyin:I
.field public static final row_email:I
.field public static final row_phone:I
.field public static final row_points:I
.field public static final rv_device_management:I
.field public static final rv_login_devices:I
.field public static final rv_messages:I
.field public static final rv_skills:I
.field public static final rv_tasks:I
.field public static final scroll_content:I
.field public static final scroll_view:I
.field public static final settings_fragment_container:I
.field public static final slogan_text:I
.field public static final splash_container:I
.field public static final stack_view:I
.field public static final step_confirm:I
.field public static final step_email_verify:I
.field public static final step_oauth_verify:I
.field public static final step_pwd_verify:I
.field public static final step_sms_verify:I
.field public static final step_submitted:I
.field public static final swipe_refresh:I
.field public static final switch_github:I
.field public static final switch_privacy_mode:I
.field public static final tab_empty_guide_ide:I
.field public static final tab_empty_guide_work:I
.field public static final title_bar:I
.field public static final toolbar:I
.field public static final tv_account_label:I
.field public static final tv_body:I
.field public static final tv_bound_products:I
.field public static final tv_char_count:I
.field public static final tv_cn_free_badge:I
.field public static final tv_cn_tier_badge:I
.field public static final tv_confirm_user_info:I
.field public static final tv_current_device:I
.field public static final tv_debug_ppe_value:I
.field public static final tv_device_id:I
.field public static final tv_device_meta:I
.field public static final tv_device_name:I
.field public static final tv_device_status:I
.field public static final tv_dialog_message:I
.field public static final tv_dialog_title:I
.field public static final tv_dot1:I
.field public static final tv_douyin_subtitle:I
.field public static final tv_email:I
.field public static final tv_email_value:I
.field public static final tv_email_verify_hint:I
.field public static final tv_empty:I
.field public static final tv_empty_guide_ide_tab:I
.field public static final tv_empty_guide_work_tab:I
.field public static final tv_env_lane_current:I
.field public static final tv_first_bound:I
.field public static final tv_github_title:I
.field public static final tv_icp_filing:I
.field public static final tv_language_value:I
.field public static final tv_last_active:I
.field public static final tv_legal_notice:I
.field public static final tv_location:I
.field public static final tv_message:I
.field public static final tv_message_badge:I
.field public static final tv_model_filing:I
.field public static final tv_model_name:I
.field public static final tv_name:I
.field public static final tv_name_value:I
.field public static final tv_oauth_nickname:I
.field public static final tv_oauth_unsupported:I
.field public static final tv_oauth_verify_hint:I
.field public static final tv_passport_user_id:I
.field public static final tv_phone_subtitle:I
.field public static final tv_pin:I
.field public static final tv_points_balance:I
.field public static final tv_popup_item:I
.field public static final tv_ppe_current:I
.field public static final tv_ppe_history_label:I
.field public static final tv_privacy_desc:I
.field public static final tv_privacy_details:I
.field public static final tv_pro_badge:I
.field public static final tv_product_type:I
.field public static final tv_pwd_verify_hint:I
.field public static final tv_sms_verify_hint:I
.field public static final tv_step1_url:I
.field public static final tv_task_search_empty_text:I
.field public static final tv_theme_value:I
.field public static final tv_time:I
.field public static final tv_title:I
.field public static final tv_user_id:I
.field public static final tv_version:I
.field public static final v_badge:I
.field public static final v_unread_dot:I
.field public static final webview:I


.method private constructor <init>()void
    .registers 1
    # ins_size=1
    invoke-direct v0, Ljava/lang/Object;-><init>()V
    return-void 
.end method
