# Decompiled TRAE business class
# Source DEX: classes5.dex
.class public final Lcom/bytedance/trae/home/R$string;
.super Ljava/lang/Object;

.field public static final cmp_device_management_guide_ide_step2:I
.field public static final cmp_device_management_guide_ide_step3:I
.field public static final cmp_device_management_guide_step1:I
.field public static final cmp_device_management_guide_work_step2:I
.field public static final cmp_device_management_guide_work_step3:I
.field public static final cmp_device_management_ide_title:I
.field public static final cmp_device_management_offline:I
.field public static final cmp_device_management_online:I
.field public static final cmp_device_management_work_title:I
.field public static final cmp_trae_setting_bonus:I
.field public static final cmp_trae_setting_points:I
.field public static final cmp_trae_setting_subscribe:I
.field public static final cmp_trae_setting_theme:I
.field public static final cmp_trae_setting_theme_dark:I
.field public static final cmp_trae_setting_theme_light:I
.field public static final cmp_trae_setting_theme_system:I
.field public static final cmp_trae_setting_upgrade:I
.field public static final cmp_trae_setting_usage:I
.field public static final cmp_trae_setting_usage_price:I
.field public static final onboarding_btn_continue:I
.field public static final onboarding_btn_lets_go:I
.field public static final onboarding_title_italic_1:I
.field public static final onboarding_title_italic_2:I
.field public static final onboarding_title_italic_3:I
.field public static final onboarding_title_normal_1:I
.field public static final onboarding_title_normal_2:I
.field public static final onboarding_title_normal_3:I
.field public static final solo_context_menu_delete:I
.field public static final solo_context_menu_pin:I
.field public static final solo_context_menu_rename:I
.field public static final solo_context_menu_unpin:I
.field public static final solo_device_context_menu_unbind:I
.field public static final solo_device_delete_dialog_message:I
.field public static final solo_device_delete_dialog_title:I
.field public static final solo_device_dialog_btn_unbind:I
.field public static final solo_device_dialog_rename_title:I
.field public static final solo_device_unbind_dialog_message:I
.field public static final solo_device_unbind_dialog_title:I
.field public static final solo_dialog_btn_cancel:I
.field public static final solo_dialog_btn_confirm:I
.field public static final solo_dialog_btn_delete:I
.field public static final solo_dialog_delete_message:I
.field public static final solo_dialog_delete_title:I
.field public static final solo_dialog_rename_title:I
.field public static final solo_filter_all:I
.field public static final solo_filter_cloud:I
.field public static final solo_task_empty_hint:I
.field public static final solo_task_new_task:I
.field public static final solo_task_search_clear_content_description:I
.field public static final solo_task_search_empty_format:I
.field public static final solo_task_search_entry_content_description:I
.field public static final solo_task_search_exit_content_description:I
.field public static final solo_task_search_hint:I
.field public static final solo_task_search_loading:I
.field public static final solo_task_title:I
.field public static final solo_toast_delete_failed:I
.field public static final solo_toast_delete_success:I
.field public static final solo_toast_device_unbind_failed:I
.field public static final solo_toast_pin_failed:I
.field public static final solo_toast_pin_success:I
.field public static final solo_toast_pin_version_incompatible:I
.field public static final solo_toast_rename_failed:I
.field public static final solo_toast_rename_success:I
.field public static final solo_toast_unpaired_device_unsupported:I
.field public static final solo_toast_unpin_failed:I
.field public static final solo_toast_unpin_success:I
.field public static final splash_slogan:I
.field public static final trae_delete_after_deletion_warning:I
.field public static final trae_delete_asset_a:I
.field public static final trae_delete_asset_b:I
.field public static final trae_delete_asset_c:I
.field public static final trae_delete_check_failed:I
.field public static final trae_delete_code_hint:I
.field public static final trae_delete_condition_check_failed:I
.field public static final trae_delete_confirm_delete:I
.field public static final trae_delete_confirm_reminder:I
.field public static final trae_delete_confirm_to_delete:I
.field public static final trae_delete_dialog_message:I
.field public static final trae_delete_dialog_title:I
.field public static final trae_delete_email_hint:I
.field public static final trae_delete_email_verify_hint:I
.field public static final trae_delete_failed:I
.field public static final trae_delete_grace_period_info:I
.field public static final trae_delete_grace_period_login:I
.field public static final trae_delete_oauth_unsupported:I
.field public static final trae_delete_oauth_verify_hint:I
.field public static final trae_delete_ok_countdown:I
.field public static final trae_delete_password_hint:I
.field public static final trae_delete_pwd_verify_hint:I
.field public static final trae_delete_resend_code:I
.field public static final trae_delete_send_code:I
.field public static final trae_delete_send_code_failed:I
.field public static final trae_delete_send_code_success:I
.field public static final trae_delete_sms_no_phone:I
.field public static final trae_delete_sms_verify_hint:I
.field public static final trae_delete_success_message:I
.field public static final trae_delete_success_title:I
.field public static final trae_delete_verify_account:I
.field public static final trae_delete_verify_failed:I
.field public static final trae_delete_verify_with_google:I
.field public static final trae_device_target_select_title:I
.field public static final trae_privacy_dialog_agree:I
.field public static final trae_privacy_dialog_disagree:I
.field public static final trae_privacy_dialog_legal_notice:I
.field public static final trae_privacy_dialog_message:I
.field public static final trae_privacy_dialog_privacy:I
.field public static final trae_privacy_dialog_terms:I
.field public static final trae_privacy_dialog_title:I
.field public static final trae_setting_about:I
.field public static final trae_setting_about_community:I
.field public static final trae_setting_about_contact:I
.field public static final trae_setting_about_help:I
.field public static final trae_setting_about_icp_filing:I
.field public static final trae_setting_about_opensource:I
.field public static final trae_setting_about_permission_usage:I
.field public static final trae_setting_about_privacy:I
.field public static final trae_setting_about_terms:I
.field public static final trae_setting_about_title:I
.field public static final trae_setting_about_version:I
.field public static final trae_setting_account:I
.field public static final trae_setting_add_device_btn:I
.field public static final trae_setting_add_device_subtitle:I
.field public static final trae_setting_add_device_title:I
.field public static final trae_setting_avatar_unsupported_format:I
.field public static final trae_setting_avatar_update_failed:I
.field public static final trae_setting_avatar_update_success:I
.field public static final trae_setting_bind:I
.field public static final trae_setting_bind_phone:I
.field public static final trae_setting_bonus:I
.field public static final trae_setting_business_license:I
.field public static final trae_setting_bytecloud_badge:I
.field public static final trae_setting_cancel:I
.field public static final trae_setting_change_bind:I
.field public static final trae_setting_connector_connect_failed:I
.field public static final trae_setting_connector_connect_success:I
.field public static final trae_setting_connector_connecting:I
.field public static final trae_setting_connector_disconnect_failed:I
.field public static final trae_setting_connector_disconnect_success:I
.field public static final trae_setting_connector_disconnecting:I
.field public static final trae_setting_connector_github:I
.field public static final trae_setting_connector_github_subtitle:I
.field public static final trae_setting_connector_manage_github:I
.field public static final trae_setting_connectors:I
.field public static final trae_setting_connectors_desc:I
.field public static final trae_setting_debug:I
.field public static final trae_setting_debug_add_header:I
.field public static final trae_setting_debug_alog_desc:I
.field public static final trae_setting_debug_alog_failed:I
.field public static final trae_setting_debug_alog_success:I
.field public static final trae_setting_debug_alog_title:I
.field public static final trae_setting_debug_alog_upload:I
.field public static final trae_setting_debug_alog_uploading:I
.field public static final trae_setting_debug_billing_prompt_cache_clear:I
.field public static final trae_setting_debug_billing_prompt_cache_cleared:I
.field public static final trae_setting_debug_billing_prompt_cache_desc:I
.field public static final trae_setting_debug_billing_prompt_cache_title:I
.field public static final trae_setting_debug_clear:I
.field public static final trae_setting_debug_clear_all:I
.field public static final trae_setting_debug_copy_device_info:I
.field public static final trae_setting_debug_custom_header_added:I
.field public static final trae_setting_debug_custom_header_cleared:I
.field public static final trae_setting_debug_custom_header_empty:I
.field public static final trae_setting_debug_custom_header_key_hint:I
.field public static final trae_setting_debug_custom_header_value_hint:I
.field public static final trae_setting_debug_custom_headers:I
.field public static final trae_setting_debug_custom_headers_desc:I
.field public static final trae_setting_debug_device_info:I
.field public static final trae_setting_debug_device_info_copied:I
.field public static final trae_setting_debug_env_lane:I
.field public static final trae_setting_debug_env_lane_current:I
.field public static final trae_setting_debug_env_lane_default:I
.field public static final trae_setting_debug_env_lane_hint:I
.field public static final trae_setting_debug_env_lane_reset:I
.field public static final trae_setting_debug_env_lane_saved:I
.field public static final trae_setting_debug_login_devices:I
.field public static final trae_setting_debug_login_devices_current:I
.field public static final trae_setting_debug_login_devices_empty:I
.field public static final trae_setting_debug_login_devices_first_bound:I
.field public static final trae_setting_debug_login_devices_last_active:I
.field public static final trae_setting_debug_login_devices_load_failed:I
.field public static final trae_setting_debug_login_devices_products:I
.field public static final trae_setting_debug_login_devices_unknown:I
.field public static final trae_setting_debug_login_devices_version:I
.field public static final trae_setting_debug_ppe_env:I
.field public static final trae_setting_debug_ppe_env_cleared:I
.field public static final trae_setting_debug_ppe_env_hint:I
.field public static final trae_setting_debug_ppe_env_not_set:I
.field public static final trae_setting_debug_ppe_env_saved:I
.field public static final trae_setting_debug_ppe_history:I
.field public static final trae_setting_debug_view_login_devices:I
.field public static final trae_setting_delete_account:I
.field public static final trae_setting_device_empty_tab_ide:I
.field public static final trae_setting_device_empty_tab_work:I
.field public static final trae_setting_device_management:I
.field public static final trae_setting_device_online:I
.field public static final trae_setting_douyin_account:I
.field public static final trae_setting_douyin_bind_conflict:I
.field public static final trae_setting_douyin_bind_success:I
.field public static final trae_setting_douyin_bound:I
.field public static final trae_setting_douyin_last_method:I
.field public static final trae_setting_douyin_operation_failed:I
.field public static final trae_setting_douyin_unbind_confirm:I
.field public static final trae_setting_douyin_unbind_message:I
.field public static final trae_setting_douyin_unbind_success:I
.field public static final trae_setting_douyin_unbind_title:I
.field public static final trae_setting_douyin_unbound:I
.field public static final trae_setting_edit_avatar:I
.field public static final trae_setting_edit_name:I
.field public static final trae_setting_edit_profile:I
.field public static final trae_setting_email:I
.field public static final trae_setting_enter_name_hint:I
.field public static final trae_setting_icp_filing:I
.field public static final trae_setting_lang_chinese:I
.field public static final trae_setting_lang_english:I
.field public static final trae_setting_lang_japanese:I
.field public static final trae_setting_language:I
.field public static final trae_setting_logout:I
.field public static final trae_setting_logout_confirm_message:I
.field public static final trae_setting_messages:I
.field public static final trae_setting_model_filing:I
.field public static final trae_setting_model_name:I
.field public static final trae_setting_name:I
.field public static final trae_setting_name_char_count:I
.field public static final trae_setting_name_empty_hint:I
.field public static final trae_setting_name_no_spaces:I
.field public static final trae_setting_name_too_long:I
.field public static final trae_setting_name_update_failed:I
.field public static final trae_setting_name_update_success:I
.field public static final trae_setting_no_devices:I
.field public static final trae_setting_not_bound:I
.field public static final trae_setting_notification:I
.field public static final trae_setting_notification_dialog_confirm:I
.field public static final trae_setting_notification_dialog_message:I
.field public static final trae_setting_notification_dialog_title:I
.field public static final trae_setting_ok:I
.field public static final trae_setting_personal_info_list:I
.field public static final trae_setting_phone:I
.field public static final trae_setting_points:I
.field public static final trae_setting_privacy_ai_data_usage:I
.field public static final trae_setting_privacy_ai_data_usage_off:I
.field public static final trae_setting_privacy_ai_data_usage_on:I
.field public static final trae_setting_privacy_camera:I
.field public static final trae_setting_privacy_camera_photo:I
.field public static final trae_setting_privacy_clipboard:I
.field public static final trae_setting_privacy_desc:I
.field public static final trae_setting_privacy_details:I
.field public static final trae_setting_privacy_dialog_btn_cancel:I
.field public static final trae_setting_privacy_dialog_btn_confirm:I
.field public static final trae_setting_privacy_dialog_desc_camera_photo:I
.field public static final trae_setting_privacy_dialog_desc_clipboard:I
.field public static final trae_setting_privacy_dialog_desc_file_access:I
.field public static final trae_setting_privacy_dialog_desc_microphone:I
.field public static final trae_setting_privacy_dialog_desc_more:I
.field public static final trae_setting_privacy_dialog_desc_photo:I
.field public static final trae_setting_privacy_dialog_desc_push:I
.field public static final trae_setting_privacy_dialog_desc_recording:I
.field public static final trae_setting_privacy_dialog_title_camera_photo:I
.field public static final trae_setting_privacy_dialog_title_clipboard:I
.field public static final trae_setting_privacy_dialog_title_file_access:I
.field public static final trae_setting_privacy_dialog_title_microphone:I
.field public static final trae_setting_privacy_dialog_title_more:I
.field public static final trae_setting_privacy_dialog_title_photo:I
.field public static final trae_setting_privacy_dialog_title_push:I
.field public static final trae_setting_privacy_dialog_title_recording:I
.field public static final trae_setting_privacy_file_access:I
.field public static final trae_setting_privacy_go_settings:I
.field public static final trae_setting_privacy_location:I
.field public static final trae_setting_privacy_microphone:I
.field public static final trae_setting_privacy_mode:I
.field public static final trae_setting_privacy_mode_toggle_failed:I
.field public static final trae_setting_privacy_more:I
.field public static final trae_setting_privacy_permission:I
.field public static final trae_setting_privacy_personalized:I
.field public static final trae_setting_privacy_photo:I
.field public static final trae_setting_privacy_push:I
.field public static final trae_setting_privacy_recording:I
.field public static final trae_setting_privacy_section_data:I
.field public static final trae_setting_privacy_section_system:I
.field public static final trae_setting_pro:I
.field public static final trae_setting_saas_team_flagship_badge:I
.field public static final trae_setting_saas_team_group_badge:I
.field public static final trae_setting_save:I
.field public static final trae_setting_scanning:I
.field public static final trae_setting_share_list:I
.field public static final trae_setting_subscribe:I
.field public static final trae_setting_theme:I
.field public static final trae_setting_theme_dark:I
.field public static final trae_setting_theme_light:I
.field public static final trae_setting_theme_system:I
.field public static final trae_setting_title:I
.field public static final trae_setting_unbind:I
.field public static final trae_setting_update:I
.field public static final trae_setting_upgrade:I
.field public static final trae_setting_url_copied:I
.field public static final trae_setting_usage:I
.field public static final trae_setting_usage_price:I
.field public static final trae_site_message_delete:I
.field public static final trae_site_message_empty:I
.field public static final trae_site_message_load_failed:I
.field public static final trae_site_message_settings_title:I
.field public static final trae_site_message_settings_update_failed:I
.field public static final trae_site_message_title:I
.field public static final trae_site_message_yesterday:I
.field public static final trae_tab_mine:I
.field public static final trae_tab_task_list:I


.method private constructor <init>()void
    .registers 1
    # ins_size=1
    invoke-direct v0, Ljava/lang/Object;-><init>()V
    return-void 
.end method
