# Decompiled TRAE business class
# Source DEX: classes5.dex
.class public final Lcom/bytedance/trae/common_ui/R$color;
.super Ljava/lang/Object;

.field public static final trae_accent_accent_amber:I
.field public static final trae_accent_accent_blue:I
.field public static final trae_accent_accent_coral:I
.field public static final trae_accent_accent_cyan:I
.field public static final trae_accent_accent_lime:I
.field public static final trae_accent_accent_magenta:I
.field public static final trae_accent_accent_skill:I
.field public static final trae_accent_accent_slate:I
.field public static final trae_accent_accent_teal:I
.field public static final trae_accent_accent_violet:I
.field public static final trae_bg_bg_base_default:I
.field public static final trae_bg_bg_base_secondary:I
.field public static final trae_bg_bg_base_tertiary:I
.field public static final trae_bg_bg_brand:I
.field public static final trae_bg_bg_brand_active:I
.field public static final trae_bg_bg_brand_disabled:I
.field public static final trae_bg_bg_brand_hover:I
.field public static final trae_bg_bg_brand_popup:I
.field public static final trae_bg_bg_card:I
.field public static final trae_bg_bg_invert:I
.field public static final trae_bg_bg_invert_active:I
.field public static final trae_bg_bg_invert_disabled:I
.field public static final trae_bg_bg_menu:I
.field public static final trae_bg_bg_overlay_l1:I
.field public static final trae_bg_bg_overlay_l2:I
.field public static final trae_bg_bg_overlay_l3:I
.field public static final trae_bg_bg_overlay_l4:I
.field public static final trae_bg_bg_tooltip:I
.field public static final trae_bg_bg_white:I
.field public static final trae_border_border_brand:I
.field public static final trae_border_border_contrast:I
.field public static final trae_border_border_neutral_l1:I
.field public static final trae_border_border_neutral_l2:I
.field public static final trae_border_border_neutral_l3:I
.field public static final trae_brainstorm_action_shadow:I
.field public static final trae_brand_blue_100:I
.field public static final trae_brand_blue_1000:I
.field public static final trae_brand_blue_200:I
.field public static final trae_brand_blue_300:I
.field public static final trae_brand_blue_400:I
.field public static final trae_brand_blue_500:I
.field public static final trae_brand_blue_600:I
.field public static final trae_brand_blue_700:I
.field public static final trae_brand_blue_800:I
.field public static final trae_brand_blue_900:I
.field public static final trae_brand_blue_grey_100:I
.field public static final trae_brand_blue_grey_1000:I
.field public static final trae_brand_blue_grey_200:I
.field public static final trae_brand_blue_grey_300:I
.field public static final trae_brand_blue_grey_400:I
.field public static final trae_brand_blue_grey_500:I
.field public static final trae_brand_blue_grey_600:I
.field public static final trae_brand_blue_grey_700:I
.field public static final trae_brand_blue_grey_800:I
.field public static final trae_brand_blue_grey_900:I
.field public static final trae_brand_brand_100:I
.field public static final trae_brand_brand_200:I
.field public static final trae_brand_brand_300:I
.field public static final trae_brand_brand_400:I
.field public static final trae_brand_brand_50:I
.field public static final trae_brand_brand_500:I
.field public static final trae_brand_brand_600:I
.field public static final trae_brand_brand_700:I
.field public static final trae_brand_brand_800:I
.field public static final trae_brand_brand_900:I
.field public static final trae_brand_brand_950:I
.field public static final trae_brand_brand_grey_100:I
.field public static final trae_brand_brand_grey_200:I
.field public static final trae_brand_brand_grey_300:I
.field public static final trae_brand_brand_grey_400:I
.field public static final trae_brand_brand_grey_50:I
.field public static final trae_brand_brand_grey_500:I
.field public static final trae_brand_brand_grey_600:I
.field public static final trae_brand_brand_grey_700:I
.field public static final trae_brand_brand_grey_800:I
.field public static final trae_brand_brand_grey_900:I
.field public static final trae_brand_brand_grey_950:I
.field public static final trae_brand_brand_purple_100:I
.field public static final trae_brand_brand_purple_200:I
.field public static final trae_brand_brand_purple_300:I
.field public static final trae_brand_brand_purple_400:I
.field public static final trae_brand_brand_purple_50:I
.field public static final trae_brand_brand_purple_500:I
.field public static final trae_brand_brand_purple_600:I
.field public static final trae_brand_brand_purple_700:I
.field public static final trae_brand_brand_purple_800:I
.field public static final trae_brand_brand_purple_900:I
.field public static final trae_brand_brand_purple_950:I
.field public static final trae_brand_green_grey_100:I
.field public static final trae_brand_green_grey_1000:I
.field public static final trae_brand_green_grey_200:I
.field public static final trae_brand_green_grey_300:I
.field public static final trae_brand_green_grey_400:I
.field public static final trae_brand_green_grey_500:I
.field public static final trae_brand_green_grey_600:I
.field public static final trae_brand_green_grey_700:I
.field public static final trae_brand_green_grey_800:I
.field public static final trae_brand_green_grey_900:I
.field public static final trae_brand_neutral_grey_100:I
.field public static final trae_brand_neutral_grey_1000:I
.field public static final trae_brand_neutral_grey_200:I
.field public static final trae_brand_neutral_grey_300:I
.field public static final trae_brand_neutral_grey_400:I
.field public static final trae_brand_neutral_grey_500:I
.field public static final trae_brand_neutral_grey_600:I
.field public static final trae_brand_neutral_grey_700:I
.field public static final trae_brand_neutral_grey_800:I
.field public static final trae_brand_neutral_grey_900:I
.field public static final trae_brand_purple_100:I
.field public static final trae_brand_purple_1000:I
.field public static final trae_brand_purple_200:I
.field public static final trae_brand_purple_300:I
.field public static final trae_brand_purple_400:I
.field public static final trae_brand_purple_500:I
.field public static final trae_brand_purple_600:I
.field public static final trae_brand_purple_700:I
.field public static final trae_brand_purple_800:I
.field public static final trae_brand_purple_900:I
.field public static final trae_brand_red_100:I
.field public static final trae_brand_red_1000:I
.field public static final trae_brand_red_200:I
.field public static final trae_brand_red_300:I
.field public static final trae_brand_red_400:I
.field public static final trae_brand_red_500:I
.field public static final trae_brand_red_600:I
.field public static final trae_brand_red_700:I
.field public static final trae_brand_red_800:I
.field public static final trae_brand_red_900:I
.field public static final trae_brand_sand_grey_100:I
.field public static final trae_brand_sand_grey_500:I
.field public static final trae_brand_trae_green_100:I
.field public static final trae_brand_trae_green_1000:I
.field public static final trae_brand_trae_green_200:I
.field public static final trae_brand_trae_green_300:I
.field public static final trae_brand_trae_green_400:I
.field public static final trae_brand_trae_green_500:I
.field public static final trae_brand_trae_green_600:I
.field public static final trae_brand_trae_green_700:I
.field public static final trae_brand_trae_green_800:I
.field public static final trae_brand_trae_green_900:I
.field public static final trae_brand_yellow_100:I
.field public static final trae_brand_yellow_1000:I
.field public static final trae_brand_yellow_200:I
.field public static final trae_brand_yellow_300:I
.field public static final trae_brand_yellow_400:I
.field public static final trae_brand_yellow_500:I
.field public static final trae_brand_yellow_600:I
.field public static final trae_brand_yellow_700:I
.field public static final trae_brand_yellow_800:I
.field public static final trae_brand_yellow_900:I
.field public static final trae_chat_user_bubble_gradient:I
.field public static final trae_code_code_action:I
.field public static final trae_code_code_attribute:I
.field public static final trae_code_code_constant:I
.field public static final trae_code_code_doc:I
.field public static final trae_code_code_function:I
.field public static final trae_code_code_instruction:I
.field public static final trae_code_code_link:I
.field public static final trae_code_code_number:I
.field public static final trae_code_code_parameter:I
.field public static final trae_code_code_tag:I
.field public static final trae_code_code_text:I
.field public static final trae_context_menu_shadow:I
.field public static final trae_custom_dialog_btn_default_bg:I
.field public static final trae_custom_dialog_input_bg:I
.field public static final trae_custom_dialog_message_text:I
.field public static final trae_icon_icon_brand:I
.field public static final trae_icon_icon_brand_active:I
.field public static final trae_icon_icon_brand_hover_sub:I
.field public static final trae_icon_icon_default:I
.field public static final trae_icon_icon_default_active:I
.field public static final trae_icon_icon_disabled:I
.field public static final trae_icon_icon_onaccent:I
.field public static final trae_icon_icon_onbrand:I
.field public static final trae_icon_icon_secondary:I
.field public static final trae_icon_icon_secondary_active:I
.field public static final trae_icon_icon_tertiary:I
.field public static final trae_icon_icon_white:I
.field public static final trae_query_tag_bg_blue:I
.field public static final trae_query_tag_bg_dark_purple:I
.field public static final trae_query_tag_bg_grey:I
.field public static final trae_query_tag_bg_purple:I
.field public static final trae_query_tag_text_blue:I
.field public static final trae_query_tag_text_dark_purple:I
.field public static final trae_query_tag_text_grey:I
.field public static final trae_query_tag_text_purple:I
.field public static final trae_spec_color:I
.field public static final trae_special_balck:I
.field public static final trae_special_bgtabsoverlay:I
.field public static final trae_special_black:I
.field public static final trae_special_trae_green:I
.field public static final trae_special_white:I
.field public static final trae_status_alert_active:I
.field public static final trae_status_alert_default:I
.field public static final trae_status_alert_surface_l1:I
.field public static final trae_status_alert_surface_l2:I
.field public static final trae_status_alert_surface_l3:I
.field public static final trae_status_error_active:I
.field public static final trae_status_error_default:I
.field public static final trae_status_error_hover:I
.field public static final trae_status_error_surface_l1:I
.field public static final trae_status_error_surface_l2:I
.field public static final trae_status_error_surface_l3:I
.field public static final trae_status_info_default:I
.field public static final trae_status_info_surface_l1:I
.field public static final trae_status_primary_active:I
.field public static final trae_status_primary_default:I
.field public static final trae_status_primary_hover:I
.field public static final trae_status_primary_surface_l1:I
.field public static final trae_status_primary_surface_l2:I
.field public static final trae_status_primary_surface_l3:I
.field public static final trae_status_success_active:I
.field public static final trae_status_success_default:I
.field public static final trae_status_success_hover:I
.field public static final trae_status_success_surface_l1:I
.field public static final trae_status_success_surface_l2:I
.field public static final trae_status_success_surface_l3:I
.field public static final trae_status_warning_active:I
.field public static final trae_status_warning_default:I
.field public static final trae_status_warning_surface_l1:I
.field public static final trae_status_warning_surface_l2:I
.field public static final trae_status_warning_surface_l3:I
.field public static final trae_text_text_brand:I
.field public static final trae_text_text_brand_active:I
.field public static final trae_text_text_default:I
.field public static final trae_text_text_default_active:I
.field public static final trae_text_text_disabled:I
.field public static final trae_text_text_onaccent:I
.field public static final trae_text_text_onbrand:I
.field public static final trae_text_text_secondary:I
.field public static final trae_text_text_secondary_active:I
.field public static final trae_text_text_tertiary:I
.field public static final trae_text_text_white:I
.field public static final trae_title_bar_action_bg:I
.field public static final trae_title_bar_grabber:I
.field public static final trae_title_bar_shadow:I
.field public static final trae_viz_viz_series_amber:I
.field public static final trae_viz_viz_series_coral:I
.field public static final trae_viz_viz_series_indigo:I
.field public static final trae_viz_viz_series_lime:I
.field public static final trae_viz_viz_series_magenta:I
.field public static final trae_viz_viz_series_mint:I
.field public static final trae_viz_viz_series_sky:I
.field public static final trae_viz_viz_series_slate:I
.field public static final trae_viz_viz_series_teal:I
.field public static final trae_viz_viz_series_violet:I
.field public static final trae_viz_viz_ui_bg_chart:I
.field public static final trae_viz_viz_ui_bg_tooltip:I
.field public static final trae_viz_viz_ui_chart_axis:I
.field public static final trae_viz_viz_ui_chart_subtitle:I
.field public static final trae_viz_viz_ui_chart_tick:I
.field public static final trae_viz_viz_ui_chart_title:I
.field public static final trae_viz_viz_ui_legend_label:I
.field public static final trae_viz_viz_ui_legend_value:I


.method private constructor <init>()void
    .registers 1
    # ins_size=1
    invoke-direct v0, Ljava/lang/Object;-><init>()V
    return-void 
.end method
