# Decompiled TRAE business class
# Source DEX: classes5.dex
.class public final Lcom/bytedance/trae/common_ui/R$dimen;
.super Ljava/lang/Object;

.field public static final trae_artifact_preview_error_icon_size:I
.field public static final trae_artifact_preview_loading_indicator_size:I
.field public static final trae_artifact_preview_reload_button_padding_horizontal:I
.field public static final trae_artifact_preview_reload_button_padding_vertical:I
.field public static final trae_artifact_preview_reload_button_radius:I
.field public static final trae_artifact_preview_state_gap:I
.field public static final trae_artifact_preview_state_horizontal_padding:I
.field public static final trae_body_base_font_size_sp:I
.field public static final trae_body_base_line_height_dp:I
.field public static final trae_body_base_strong_font_size_sp:I
.field public static final trae_body_base_strong_line_height_dp:I
.field public static final trae_body_body_base_font_size_sp:I
.field public static final trae_body_body_base_line_height_dp:I
.field public static final trae_body_body_base_md_font_size_sp:I
.field public static final trae_body_body_base_md_line_height_dp:I
.field public static final trae_body_body_base_strong_font_size_sp:I
.field public static final trae_body_body_base_strong_line_height_dp:I
.field public static final trae_body_body_sm_font_size_sp:I
.field public static final trae_body_body_sm_line_height_dp:I
.field public static final trae_body_body_sm_md_font_size_sp:I
.field public static final trae_body_body_sm_md_line_height_dp:I
.field public static final trae_body_body_sm_strong_font_size_sp:I
.field public static final trae_body_body_sm_strong_line_height_dp:I
.field public static final trae_body_body_xs_font_size_sp:I
.field public static final trae_body_body_xs_line_height_dp:I
.field public static final trae_body_body_xs_md_font_size_sp:I
.field public static final trae_body_body_xs_md_line_height_dp:I
.field public static final trae_body_body_xs_strong_font_size_sp:I
.field public static final trae_body_body_xs_strong_line_height_dp:I
.field public static final trae_body_md_font_size_sp:I
.field public static final trae_body_md_line_height_dp:I
.field public static final trae_body_md_strong_font_size_sp:I
.field public static final trae_body_md_strong_line_height_dp:I
.field public static final trae_body_sm_font_size_sp:I
.field public static final trae_body_sm_line_height_dp:I
.field public static final trae_body_sm_strong_font_size_sp:I
.field public static final trae_body_sm_strong_line_height_dp:I
.field public static final trae_body_xs_font_size_sp:I
.field public static final trae_body_xs_line_height_dp:I
.field public static final trae_caption_caption_base_font_size_sp:I
.field public static final trae_caption_caption_base_line_height_dp:I
.field public static final trae_caption_caption_base_strong_font_size_sp:I
.field public static final trae_caption_caption_base_strong_line_height_dp:I
.field public static final trae_caption_caption_xs_font_size_sp:I
.field public static final trae_caption_caption_xs_line_height_dp:I
.field public static final trae_caption_caption_xs_strong_font_size_sp:I
.field public static final trae_caption_caption_xs_strong_line_height_dp:I
.field public static final trae_code_code_base_font_size_sp:I
.field public static final trae_code_code_base_line_height_dp:I
.field public static final trae_code_code_sm_font_size_sp:I
.field public static final trae_code_code_sm_line_height_dp:I
.field public static final trae_code_code_xs_font_size_sp:I
.field public static final trae_code_code_xs_line_height_dp:I
.field public static final trae_code_editor_font_size_sp:I
.field public static final trae_code_editor_line_height_dp:I
.field public static final trae_code_terminal_font_size_sp:I
.field public static final trae_code_terminal_line_height_dp:I
.field public static final trae_context_menu_anchor_gap:I
.field public static final trae_context_menu_detail_icon_text_gap:I
.field public static final trae_context_menu_detail_vertical_padding:I
.field public static final trae_context_menu_detail_width:I
.field public static final trae_context_menu_divider_height:I
.field public static final trae_context_menu_elevation:I
.field public static final trae_context_menu_icon_size:I
.field public static final trae_context_menu_item_height:I
.field public static final trae_context_menu_item_horizontal_padding:I
.field public static final trae_context_menu_radius:I
.field public static final trae_context_menu_shadow_blur_radius:I
.field public static final trae_context_menu_shadow_offset_y:I
.field public static final trae_context_menu_shadow_padding_bottom:I
.field public static final trae_context_menu_shadow_padding_horizontal:I
.field public static final trae_context_menu_shadow_padding_top:I
.field public static final trae_context_menu_text_margin_start:I
.field public static final trae_context_menu_vertical_padding:I
.field public static final trae_context_menu_width:I
.field public static final trae_font_size_sp:I
.field public static final trae_footnote_footnote_font_size_sp:I
.field public static final trae_footnote_footnote_line_height_dp:I
.field public static final trae_footnote_footnote_strong_font_size_sp:I
.field public static final trae_footnote_footnote_strong_line_height_dp:I
.field public static final trae_heading_2xl_font_size_sp:I
.field public static final trae_heading_2xl_line_height_dp:I
.field public static final trae_heading_2xs_font_size_sp:I
.field public static final trae_heading_2xs_line_height_dp:I
.field public static final trae_heading_3xl_font_size_sp:I
.field public static final trae_heading_3xl_line_height_dp:I
.field public static final trae_heading_3xs_font_size_sp:I
.field public static final trae_heading_3xs_line_height_dp:I
.field public static final trae_heading_heading_2xl_font_size_sp:I
.field public static final trae_heading_heading_2xl_line_height_dp:I
.field public static final trae_heading_heading_2xl_strong_font_size_sp:I
.field public static final trae_heading_heading_2xl_strong_line_height_dp:I
.field public static final trae_heading_heading_3xl_font_size_sp:I
.field public static final trae_heading_heading_3xl_line_height_dp:I
.field public static final trae_heading_heading_3xl_strong_font_size_sp:I
.field public static final trae_heading_heading_3xl_strong_line_height_dp:I
.field public static final trae_heading_heading_lg_font_size_sp:I
.field public static final trae_heading_heading_lg_line_height_dp:I
.field public static final trae_heading_heading_lg_strong_font_size_sp:I
.field public static final trae_heading_heading_lg_strong_line_height_dp:I
.field public static final trae_heading_heading_m_font_size_sp:I
.field public static final trae_heading_heading_m_line_height_dp:I
.field public static final trae_heading_heading_m_strong_font_size_sp:I
.field public static final trae_heading_heading_m_strong_line_height_dp:I
.field public static final trae_heading_heading_xl_font_size_sp:I
.field public static final trae_heading_heading_xl_line_height_dp:I
.field public static final trae_heading_heading_xl_strong_font_size_sp:I
.field public static final trae_heading_heading_xl_strong_line_height_dp:I
.field public static final trae_heading_lg_font_size_sp:I
.field public static final trae_heading_lg_line_height_dp:I
.field public static final trae_heading_md_font_size_sp:I
.field public static final trae_heading_md_line_height_dp:I
.field public static final trae_heading_sm_font_size_sp:I
.field public static final trae_heading_sm_line_height_dp:I
.field public static final trae_heading_xl_font_size_sp:I
.field public static final trae_heading_xl_line_height_dp:I
.field public static final trae_heading_xs_font_size_sp:I
.field public static final trae_heading_xs_line_height_dp:I
.field public static final trae_line_height_dp:I
.field public static final trae_loading_view_elevation:I
.field public static final trae_title_bar_action_gap:I
.field public static final trae_title_bar_action_size:I
.field public static final trae_title_bar_detail_icon_size:I
.field public static final trae_title_bar_detail_subtitle_gap:I
.field public static final trae_title_bar_detail_title_gap:I
.field public static final trae_title_bar_download_icon_size:I
.field public static final trae_title_bar_elevation:I
.field public static final trae_title_bar_grabber_container_height:I
.field public static final trae_title_bar_grabber_height:I
.field public static final trae_title_bar_grabber_width:I
.field public static final trae_title_bar_horizontal_padding:I
.field public static final trae_title_bar_icon_size:I
.field public static final trae_title_bar_operation_height:I
.field public static final trae_title_bar_operation_margin_end:I
.field public static final trae_title_bar_operation_radius:I
.field public static final trae_title_bar_operation_width:I
.field public static final trae_title_bar_page_height:I
.field public static final trae_title_bar_segment_padding:I
.field public static final trae_title_bar_segment_selected_width:I
.field public static final trae_title_bar_segment_shadow_blur_radius:I
.field public static final trae_title_bar_segment_slot_width:I
.field public static final trae_title_bar_segment_width:I
.field public static final trae_title_bar_shadow_blur_radius:I
.field public static final trae_title_bar_shadow_offset_y:I
.field public static final trae_title_bar_sheet_content_height:I
.field public static final trae_title_bar_sheet_height:I
.field public static final trae_title_bar_task_action_padding_horizontal:I
.field public static final trae_title_bar_task_action_width:I
.field public static final trae_title_bar_task_avatar_badge_margin_bottom:I
.field public static final trae_title_bar_task_avatar_badge_margin_end:I
.field public static final trae_title_bar_task_avatar_badge_size:I
.field public static final trae_title_bar_task_avatar_size:I
.field public static final trae_title_bar_task_height:I
.field public static final trae_title_bar_task_title_icon_gap:I
.field public static final trae_title_bar_task_title_icon_size:I
.field public static final trae_title_bar_title_side_gap:I
.field public static final trae_video_artifact_card_border_width:I
.field public static final trae_video_artifact_card_bottom_margin:I
.field public static final trae_video_artifact_card_divider_height:I
.field public static final trae_video_artifact_card_duration_bottom_margin:I
.field public static final trae_video_artifact_card_duration_end_margin:I
.field public static final trae_video_artifact_card_duration_height:I
.field public static final trae_video_artifact_card_duration_horizontal_padding:I
.field public static final trae_video_artifact_card_file_icon_container_size:I
.field public static final trae_video_artifact_card_file_icon_size:I
.field public static final trae_video_artifact_card_gradient_height:I
.field public static final trae_video_artifact_card_header_height:I
.field public static final trae_video_artifact_card_header_horizontal_padding:I
.field public static final trae_video_artifact_card_header_vertical_padding:I
.field public static final trae_video_artifact_card_play_button_padding:I
.field public static final trae_video_artifact_card_play_button_size:I
.field public static final trae_video_artifact_card_play_icon_size:I
.field public static final trae_video_artifact_card_preview_height:I
.field public static final trae_video_artifact_card_radius:I
.field public static final trae_video_artifact_card_title_gap:I
.field public static final trae_video_preview_control_bottom_margin:I
.field public static final trae_video_preview_control_content_height:I
.field public static final trae_video_preview_control_gap:I
.field public static final trae_video_preview_control_height:I
.field public static final trae_video_preview_control_horizontal_margin:I
.field public static final trae_video_preview_control_padding_end:I
.field public static final trae_video_preview_control_padding_start:I
.field public static final trae_video_preview_control_padding_vertical:I
.field public static final trae_video_preview_control_radius:I
.field public static final trae_video_preview_control_text_row_height:I
.field public static final trae_video_preview_play_icon_size:I
.field public static final trae_video_preview_play_touch_size:I
.field public static final trae_video_preview_progress_height:I
.field public static final trae_video_preview_progress_horizontal_inset:I
.field public static final trae_video_preview_progress_thumb_size:I
.field public static final trae_video_preview_progress_track_height:I
.field public static final trae_video_preview_speed_menu_item_height:I
.field public static final trae_video_preview_speed_menu_radius:I
.field public static final trae_video_preview_speed_menu_width:I
.field public static final trae_video_preview_title_font_size_sp:I
.field public static final trae_video_preview_title_line_height_dp:I


.method private constructor <init>()void
    .registers 1
    # ins_size=1
    invoke-direct v0, Ljava/lang/Object;-><init>()V
    return-void 
.end method
